// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ioproxy.proto

package ioproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ExecID        string                 `protobuf:"bytes,2,opt,name=ExecID,proto3" json:"ExecID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_ioproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_ioproxy_proto_rawDescGZIP(), []int{0}
}

func (x *StateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *StateRequest) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_ioproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_ioproxy_proto_rawDescGZIP(), []int{1}
}

func (x *StateResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ExecID        string                 `protobuf:"bytes,2,opt,name=ExecID,proto3" json:"ExecID,omitempty"`
	StdinPort     uint32                 `protobuf:"varint,3,opt,name=StdinPort,proto3" json:"StdinPort,omitempty"`
	StdoutPort    uint32                 `protobuf:"varint,4,opt,name=StdoutPort,proto3" json:"StdoutPort,omitempty"`
	StderrPort    uint32                 `protobuf:"varint,5,opt,name=StderrPort,proto3" json:"StderrPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_ioproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_ioproxy_proto_rawDescGZIP(), []int{2}
}

func (x *AttachRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AttachRequest) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

func (x *AttachRequest) GetStdinPort() uint32 {
	if x != nil {
		return x.StdinPort
	}
	return 0
}

func (x *AttachRequest) GetStdoutPort() uint32 {
	if x != nil {
		return x.StdoutPort
	}
	return 0
}

func (x *AttachRequest) GetStderrPort() uint32 {
	if x != nil {
		return x.StderrPort
	}
	return 0
}

var File_ioproxy_proto protoreflect.FileDescriptor

const file_ioproxy_proto_rawDesc = "" +
	"\n" +
	"\rioproxy.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\fStateRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06ExecID\x18\x02 \x01(\tR\x06ExecID\"'\n" +
	"\rStateResponse\x12\x16\n" +
	"\x06IsOpen\x18\x01 \x01(\bR\x06IsOpen\"\x95\x01\n" +
	"\rAttachRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06ExecID\x18\x02 \x01(\tR\x06ExecID\x12\x1c\n" +
	"\tStdinPort\x18\x03 \x01(\rR\tStdinPort\x12\x1e\n" +
	"\n" +
	"StdoutPort\x18\x04 \x01(\rR\n" +
	"StdoutPort\x12\x1e\n" +
	"\n" +
	"StderrPort\x18\x05 \x01(\rR\n" +
	"StderrPort2c\n" +
	"\aIOProxy\x12&\n" +
	"\x05State\x12\r.StateRequest\x1a\x0e.StateResponse\x120\n" +
	"\x06Attach\x12\x0e.AttachRequest\x1a\x16.google.protobuf.EmptyB\vZ\t.;ioproxyb\x06proto3"

var (
	file_ioproxy_proto_rawDescOnce sync.Once
	file_ioproxy_proto_rawDescData []byte
)

func file_ioproxy_proto_rawDescGZIP() []byte {
	file_ioproxy_proto_rawDescOnce.Do(func() {
		file_ioproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioproxy_proto_rawDesc), len(file_ioproxy_proto_rawDesc)))
	})
	return file_ioproxy_proto_rawDescData
}

var file_ioproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ioproxy_proto_goTypes = []any{
	(*StateRequest)(nil),  // 0: StateRequest
	(*StateResponse)(nil), // 1: StateResponse
	(*AttachRequest)(nil), // 2: AttachRequest
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_ioproxy_proto_depIdxs = []int32{
	0, // 0: IOProxy.State:input_type -> StateRequest
	2, // 1: IOProxy.Attach:input_type -> AttachRequest
	1, // 2: IOProxy.State:output_type -> StateResponse
	3, // 3: IOProxy.Attach:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ioproxy_proto_init() }
func file_ioproxy_proto_init() {
	if File_ioproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioproxy_proto_rawDesc), len(file_ioproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ioproxy_proto_goTypes,
		DependencyIndexes: file_ioproxy_proto_depIdxs,
		MessageInfos:      file_ioproxy_proto_msgTypes,
	}.Build()
	File_ioproxy_proto = out.File
	file_ioproxy_proto_goTypes = nil
	file_ioproxy_proto_depIdxs = nil
}
