// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: firecracker.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DriveExposePolicy is used to configure the method to expose drive files.
// "COPY" is copying the files to the jail, which is the default behavior.
// "BIND" is bind-mounting the files on the jail, assuming a caller pre-configures the permissions of
// the files appropriately.
type DriveExposePolicy int32

const (
	DriveExposePolicy_COPY DriveExposePolicy = 0
	DriveExposePolicy_BIND DriveExposePolicy = 1
)

var DriveExposePolicy_name = map[int32]string{
	0: "COPY",
	1: "BIND",
}

var DriveExposePolicy_value = map[string]int32{
	"COPY": 0,
	"BIND": 1,
}

func (x DriveExposePolicy) String() string {
	return proto.EnumName(DriveExposePolicy_name, int32(x))
}

func (DriveExposePolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{0}
}

// CreateVMRequest specifies creation parameters for a new FC instance
type CreateVMRequest struct {
	// VM identifier to assign
	VMID string `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	// Specifies the machine configuration for the VM
	MachineCfg *FirecrackerMachineConfiguration `protobuf:"bytes,2,opt,name=MachineCfg,proto3" json:"MachineCfg,omitempty"`
	// Specifies the file path where the kernel image is located
	KernelImagePath string `protobuf:"bytes,3,opt,name=KernelImagePath,proto3" json:"KernelImagePath,omitempty"`
	// Specifies the commandline arguments that should be passed to the kernel
	KernelArgs string `protobuf:"bytes,4,opt,name=KernelArgs,proto3" json:"KernelArgs,omitempty"`
	// Specifies drive containing the rootfs of the VM
	RootDrive *FirecrackerRootDrive `protobuf:"bytes,5,opt,name=RootDrive,proto3" json:"RootDrive,omitempty"`
	// Specifies additional drives whose contents will be mounted inside the VM on boot.
	DriveMounts []*FirecrackerDriveMount `protobuf:"bytes,6,rep,name=DriveMounts,proto3" json:"DriveMounts,omitempty"`
	// Specifies the networking configuration for a VM
	NetworkInterfaces []*FirecrackerNetworkInterface `protobuf:"bytes,7,rep,name=NetworkInterfaces,proto3" json:"NetworkInterfaces,omitempty"`
	// The number of dummy drives to reserve in advance before running FC instance.
	ContainerCount int32 `protobuf:"varint,8,opt,name=ContainerCount,proto3" json:"ContainerCount,omitempty"`
	// Whether the VM should exit after all tasks running in it have been deleted.
	ExitAfterAllTasksDeleted bool                      `protobuf:"varint,9,opt,name=ExitAfterAllTasksDeleted,proto3" json:"ExitAfterAllTasksDeleted,omitempty"`
	JailerConfig             *JailerConfig             `protobuf:"bytes,10,opt,name=JailerConfig,proto3" json:"JailerConfig,omitempty"`
	TimeoutSeconds           uint32                    `protobuf:"varint,11,opt,name=TimeoutSeconds,proto3" json:"TimeoutSeconds,omitempty"`
	LogFifoPath              string                    `protobuf:"bytes,12,opt,name=LogFifoPath,proto3" json:"LogFifoPath,omitempty"`
	MetricsFifoPath          string                    `protobuf:"bytes,13,opt,name=MetricsFifoPath,proto3" json:"MetricsFifoPath,omitempty"`
	BalloonDevice            *FirecrackerBalloonDevice `protobuf:"bytes,14,opt,name=BalloonDevice,proto3" json:"BalloonDevice,omitempty"`
	NetworkNamespace         string                    `protobuf:"bytes,15,opt,name=NetworkNamespace,proto3" json:"NetworkNamespace,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *CreateVMRequest) Reset()         { *m = CreateVMRequest{} }
func (m *CreateVMRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVMRequest) ProtoMessage()    {}
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{0}
}
func (m *CreateVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMRequest.Unmarshal(m, b)
}
func (m *CreateVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMRequest.Marshal(b, m, deterministic)
}
func (m *CreateVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMRequest.Merge(m, src)
}
func (m *CreateVMRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVMRequest.Size(m)
}
func (m *CreateVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMRequest proto.InternalMessageInfo

func (m *CreateVMRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *CreateVMRequest) GetMachineCfg() *FirecrackerMachineConfiguration {
	if m != nil {
		return m.MachineCfg
	}
	return nil
}

func (m *CreateVMRequest) GetKernelImagePath() string {
	if m != nil {
		return m.KernelImagePath
	}
	return ""
}

func (m *CreateVMRequest) GetKernelArgs() string {
	if m != nil {
		return m.KernelArgs
	}
	return ""
}

func (m *CreateVMRequest) GetRootDrive() *FirecrackerRootDrive {
	if m != nil {
		return m.RootDrive
	}
	return nil
}

func (m *CreateVMRequest) GetDriveMounts() []*FirecrackerDriveMount {
	if m != nil {
		return m.DriveMounts
	}
	return nil
}

func (m *CreateVMRequest) GetNetworkInterfaces() []*FirecrackerNetworkInterface {
	if m != nil {
		return m.NetworkInterfaces
	}
	return nil
}

func (m *CreateVMRequest) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *CreateVMRequest) GetExitAfterAllTasksDeleted() bool {
	if m != nil {
		return m.ExitAfterAllTasksDeleted
	}
	return false
}

func (m *CreateVMRequest) GetJailerConfig() *JailerConfig {
	if m != nil {
		return m.JailerConfig
	}
	return nil
}

func (m *CreateVMRequest) GetTimeoutSeconds() uint32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *CreateVMRequest) GetLogFifoPath() string {
	if m != nil {
		return m.LogFifoPath
	}
	return ""
}

func (m *CreateVMRequest) GetMetricsFifoPath() string {
	if m != nil {
		return m.MetricsFifoPath
	}
	return ""
}

func (m *CreateVMRequest) GetBalloonDevice() *FirecrackerBalloonDevice {
	if m != nil {
		return m.BalloonDevice
	}
	return nil
}

func (m *CreateVMRequest) GetNetworkNamespace() string {
	if m != nil {
		return m.NetworkNamespace
	}
	return ""
}

type CreateVMResponse struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	SocketPath           string   `protobuf:"bytes,2,opt,name=SocketPath,proto3" json:"SocketPath,omitempty"`
	LogFifoPath          string   `protobuf:"bytes,3,opt,name=LogFifoPath,proto3" json:"LogFifoPath,omitempty"`
	MetricsFifoPath      string   `protobuf:"bytes,4,opt,name=MetricsFifoPath,proto3" json:"MetricsFifoPath,omitempty"`
	CgroupPath           string   `protobuf:"bytes,5,opt,name=CgroupPath,proto3" json:"CgroupPath,omitempty"`
	UPFSockPath          string   `protobuf:"bytes,6,opt,name=UPFSockPath,proto3" json:"UPFSockPath,omitempty"`
	FirecrackerPID       string   `protobuf:"bytes,7,opt,name=FirecrackerPID,proto3" json:"FirecrackerPID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVMResponse) Reset()         { *m = CreateVMResponse{} }
func (m *CreateVMResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVMResponse) ProtoMessage()    {}
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{1}
}
func (m *CreateVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMResponse.Unmarshal(m, b)
}
func (m *CreateVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMResponse.Marshal(b, m, deterministic)
}
func (m *CreateVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMResponse.Merge(m, src)
}
func (m *CreateVMResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVMResponse.Size(m)
}
func (m *CreateVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMResponse proto.InternalMessageInfo

func (m *CreateVMResponse) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *CreateVMResponse) GetSocketPath() string {
	if m != nil {
		return m.SocketPath
	}
	return ""
}

func (m *CreateVMResponse) GetLogFifoPath() string {
	if m != nil {
		return m.LogFifoPath
	}
	return ""
}

func (m *CreateVMResponse) GetMetricsFifoPath() string {
	if m != nil {
		return m.MetricsFifoPath
	}
	return ""
}

func (m *CreateVMResponse) GetCgroupPath() string {
	if m != nil {
		return m.CgroupPath
	}
	return ""
}

func (m *CreateVMResponse) GetUPFSockPath() string {
	if m != nil {
		return m.UPFSockPath
	}
	return ""
}

func (m *CreateVMResponse) GetFirecrackerPID() string {
	if m != nil {
		return m.FirecrackerPID
	}
	return ""
}

type PauseVMRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseVMRequest) Reset()         { *m = PauseVMRequest{} }
func (m *PauseVMRequest) String() string { return proto.CompactTextString(m) }
func (*PauseVMRequest) ProtoMessage()    {}
func (*PauseVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{2}
}
func (m *PauseVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseVMRequest.Unmarshal(m, b)
}
func (m *PauseVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseVMRequest.Marshal(b, m, deterministic)
}
func (m *PauseVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseVMRequest.Merge(m, src)
}
func (m *PauseVMRequest) XXX_Size() int {
	return xxx_messageInfo_PauseVMRequest.Size(m)
}
func (m *PauseVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseVMRequest proto.InternalMessageInfo

func (m *PauseVMRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type ResumeVMRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeVMRequest) Reset()         { *m = ResumeVMRequest{} }
func (m *ResumeVMRequest) String() string { return proto.CompactTextString(m) }
func (*ResumeVMRequest) ProtoMessage()    {}
func (*ResumeVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{3}
}
func (m *ResumeVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeVMRequest.Unmarshal(m, b)
}
func (m *ResumeVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeVMRequest.Marshal(b, m, deterministic)
}
func (m *ResumeVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeVMRequest.Merge(m, src)
}
func (m *ResumeVMRequest) XXX_Size() int {
	return xxx_messageInfo_ResumeVMRequest.Size(m)
}
func (m *ResumeVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeVMRequest proto.InternalMessageInfo

func (m *ResumeVMRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type StopVMRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	TimeoutSeconds       uint32   `protobuf:"varint,2,opt,name=TimeoutSeconds,proto3" json:"TimeoutSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopVMRequest) Reset()         { *m = StopVMRequest{} }
func (m *StopVMRequest) String() string { return proto.CompactTextString(m) }
func (*StopVMRequest) ProtoMessage()    {}
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{4}
}
func (m *StopVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopVMRequest.Unmarshal(m, b)
}
func (m *StopVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopVMRequest.Marshal(b, m, deterministic)
}
func (m *StopVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopVMRequest.Merge(m, src)
}
func (m *StopVMRequest) XXX_Size() int {
	return xxx_messageInfo_StopVMRequest.Size(m)
}
func (m *StopVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopVMRequest proto.InternalMessageInfo

func (m *StopVMRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *StopVMRequest) GetTimeoutSeconds() uint32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type GetVMInfoRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVMInfoRequest) Reset()         { *m = GetVMInfoRequest{} }
func (m *GetVMInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetVMInfoRequest) ProtoMessage()    {}
func (*GetVMInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{5}
}
func (m *GetVMInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVMInfoRequest.Unmarshal(m, b)
}
func (m *GetVMInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVMInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetVMInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVMInfoRequest.Merge(m, src)
}
func (m *GetVMInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetVMInfoRequest.Size(m)
}
func (m *GetVMInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVMInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVMInfoRequest proto.InternalMessageInfo

func (m *GetVMInfoRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type GetVMInfoResponse struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	SocketPath           string   `protobuf:"bytes,2,opt,name=SocketPath,proto3" json:"SocketPath,omitempty"`
	LogFifoPath          string   `protobuf:"bytes,3,opt,name=LogFifoPath,proto3" json:"LogFifoPath,omitempty"`
	MetricsFifoPath      string   `protobuf:"bytes,4,opt,name=MetricsFifoPath,proto3" json:"MetricsFifoPath,omitempty"`
	CgroupPath           string   `protobuf:"bytes,5,opt,name=CgroupPath,proto3" json:"CgroupPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVMInfoResponse) Reset()         { *m = GetVMInfoResponse{} }
func (m *GetVMInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetVMInfoResponse) ProtoMessage()    {}
func (*GetVMInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{6}
}
func (m *GetVMInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVMInfoResponse.Unmarshal(m, b)
}
func (m *GetVMInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVMInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetVMInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVMInfoResponse.Merge(m, src)
}
func (m *GetVMInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetVMInfoResponse.Size(m)
}
func (m *GetVMInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVMInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVMInfoResponse proto.InternalMessageInfo

func (m *GetVMInfoResponse) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *GetVMInfoResponse) GetSocketPath() string {
	if m != nil {
		return m.SocketPath
	}
	return ""
}

func (m *GetVMInfoResponse) GetLogFifoPath() string {
	if m != nil {
		return m.LogFifoPath
	}
	return ""
}

func (m *GetVMInfoResponse) GetMetricsFifoPath() string {
	if m != nil {
		return m.MetricsFifoPath
	}
	return ""
}

func (m *GetVMInfoResponse) GetCgroupPath() string {
	if m != nil {
		return m.CgroupPath
	}
	return ""
}

type SetVMMetadataRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	Metadata             string   `protobuf:"bytes,2,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetVMMetadataRequest) Reset()         { *m = SetVMMetadataRequest{} }
func (m *SetVMMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*SetVMMetadataRequest) ProtoMessage()    {}
func (*SetVMMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{7}
}
func (m *SetVMMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVMMetadataRequest.Unmarshal(m, b)
}
func (m *SetVMMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVMMetadataRequest.Marshal(b, m, deterministic)
}
func (m *SetVMMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVMMetadataRequest.Merge(m, src)
}
func (m *SetVMMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_SetVMMetadataRequest.Size(m)
}
func (m *SetVMMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVMMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVMMetadataRequest proto.InternalMessageInfo

func (m *SetVMMetadataRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *SetVMMetadataRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type UpdateVMMetadataRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	Metadata             string   `protobuf:"bytes,2,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVMMetadataRequest) Reset()         { *m = UpdateVMMetadataRequest{} }
func (m *UpdateVMMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVMMetadataRequest) ProtoMessage()    {}
func (*UpdateVMMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{8}
}
func (m *UpdateVMMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVMMetadataRequest.Unmarshal(m, b)
}
func (m *UpdateVMMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVMMetadataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateVMMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVMMetadataRequest.Merge(m, src)
}
func (m *UpdateVMMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVMMetadataRequest.Size(m)
}
func (m *UpdateVMMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVMMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVMMetadataRequest proto.InternalMessageInfo

func (m *UpdateVMMetadataRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *UpdateVMMetadataRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type GetVMMetadataRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVMMetadataRequest) Reset()         { *m = GetVMMetadataRequest{} }
func (m *GetVMMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetVMMetadataRequest) ProtoMessage()    {}
func (*GetVMMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{9}
}
func (m *GetVMMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVMMetadataRequest.Unmarshal(m, b)
}
func (m *GetVMMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVMMetadataRequest.Marshal(b, m, deterministic)
}
func (m *GetVMMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVMMetadataRequest.Merge(m, src)
}
func (m *GetVMMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetVMMetadataRequest.Size(m)
}
func (m *GetVMMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVMMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVMMetadataRequest proto.InternalMessageInfo

func (m *GetVMMetadataRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type GetVMMetadataResponse struct {
	Metadata             string   `protobuf:"bytes,1,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVMMetadataResponse) Reset()         { *m = GetVMMetadataResponse{} }
func (m *GetVMMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetVMMetadataResponse) ProtoMessage()    {}
func (*GetVMMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{10}
}
func (m *GetVMMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVMMetadataResponse.Unmarshal(m, b)
}
func (m *GetVMMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVMMetadataResponse.Marshal(b, m, deterministic)
}
func (m *GetVMMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVMMetadataResponse.Merge(m, src)
}
func (m *GetVMMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetVMMetadataResponse.Size(m)
}
func (m *GetVMMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVMMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVMMetadataResponse proto.InternalMessageInfo

func (m *GetVMMetadataResponse) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type CreateSnapshotRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	SnapshotFilePath     string   `protobuf:"bytes,2,opt,name=SnapshotFilePath,proto3" json:"SnapshotFilePath,omitempty"`
	MemFilePath          string   `protobuf:"bytes,3,opt,name=MemFilePath,proto3" json:"MemFilePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSnapshotRequest) Reset()         { *m = CreateSnapshotRequest{} }
func (m *CreateSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotRequest) ProtoMessage()    {}
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{11}
}
func (m *CreateSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotRequest.Unmarshal(m, b)
}
func (m *CreateSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *CreateSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotRequest.Merge(m, src)
}
func (m *CreateSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotRequest.Size(m)
}
func (m *CreateSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotRequest proto.InternalMessageInfo

func (m *CreateSnapshotRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *CreateSnapshotRequest) GetSnapshotFilePath() string {
	if m != nil {
		return m.SnapshotFilePath
	}
	return ""
}

func (m *CreateSnapshotRequest) GetMemFilePath() string {
	if m != nil {
		return m.MemFilePath
	}
	return ""
}

type LoadSnapshotRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	SnapshotFilePath     string   `protobuf:"bytes,2,opt,name=SnapshotFilePath,proto3" json:"SnapshotFilePath,omitempty"`
	MemFilePath          string   `protobuf:"bytes,3,opt,name=MemFilePath,proto3" json:"MemFilePath,omitempty"`
	EnableUserPF         bool     `protobuf:"varint,4,opt,name=EnableUserPF,proto3" json:"EnableUserPF,omitempty"`
	NetworkNamespace     string   `protobuf:"bytes,5,opt,name=NetworkNamespace,proto3" json:"NetworkNamespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadSnapshotRequest) Reset()         { *m = LoadSnapshotRequest{} }
func (m *LoadSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*LoadSnapshotRequest) ProtoMessage()    {}
func (*LoadSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{12}
}
func (m *LoadSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadSnapshotRequest.Unmarshal(m, b)
}
func (m *LoadSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *LoadSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadSnapshotRequest.Merge(m, src)
}
func (m *LoadSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_LoadSnapshotRequest.Size(m)
}
func (m *LoadSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadSnapshotRequest proto.InternalMessageInfo

func (m *LoadSnapshotRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *LoadSnapshotRequest) GetSnapshotFilePath() string {
	if m != nil {
		return m.SnapshotFilePath
	}
	return ""
}

func (m *LoadSnapshotRequest) GetMemFilePath() string {
	if m != nil {
		return m.MemFilePath
	}
	return ""
}

func (m *LoadSnapshotRequest) GetEnableUserPF() bool {
	if m != nil {
		return m.EnableUserPF
	}
	return false
}

func (m *LoadSnapshotRequest) GetNetworkNamespace() string {
	if m != nil {
		return m.NetworkNamespace
	}
	return ""
}

type LoadResponse struct {
	FirecrackerPID       string   `protobuf:"bytes,1,opt,name=FirecrackerPID,proto3" json:"FirecrackerPID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{13}
}
func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetFirecrackerPID() string {
	if m != nil {
		return m.FirecrackerPID
	}
	return ""
}

type OffloadRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffloadRequest) Reset()         { *m = OffloadRequest{} }
func (m *OffloadRequest) String() string { return proto.CompactTextString(m) }
func (*OffloadRequest) ProtoMessage()    {}
func (*OffloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{14}
}
func (m *OffloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffloadRequest.Unmarshal(m, b)
}
func (m *OffloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffloadRequest.Marshal(b, m, deterministic)
}
func (m *OffloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffloadRequest.Merge(m, src)
}
func (m *OffloadRequest) XXX_Size() int {
	return xxx_messageInfo_OffloadRequest.Size(m)
}
func (m *OffloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OffloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OffloadRequest proto.InternalMessageInfo

func (m *OffloadRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type JailerConfig struct {
	NetNS string `protobuf:"bytes,1,opt,name=NetNS,proto3" json:"NetNS,omitempty"`
	// List of the physical numbers of the CPUs on which processes in that
	// cpuset are allowed to execute.  See List Format below for a description
	// of the format of cpus.
	//
	// The CPUs allowed to a cpuset may be changed by writing a new list to its
	// cpus file.
	// Taken from http://man7.org/linux/man-pages/man7/cpuset.7.html
	//
	// This is formatted as specified in the cpuset man page under "List Format"
	// http://man7.org/linux/man-pages/man7/cpuset.7.html
	CPUs string `protobuf:"bytes,2,opt,name=CPUs,proto3" json:"CPUs,omitempty"`
	// List of memory nodes on which processes in this cpuset are allowed to
	// allocate memory.  See List Format below for a description of the format
	// of mems.
	// Taken from http://man7.org/linux/man-pages/man7/cpuset.7.html
	//
	// This is formatted as specified in the cpuset man page under "List Format"
	// http://man7.org/linux/man-pages/man7/cpuset.7.html
	Mems string `protobuf:"bytes,3,opt,name=Mems,proto3" json:"Mems,omitempty"`
	UID  uint32 `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`
	GID  uint32 `protobuf:"varint,5,opt,name=GID,proto3" json:"GID,omitempty"`
	// CgroupPath is used to dictate where the cgroup should be located
	// relative to the cgroup directory which is
	// /sys/fs/cgroup/cpu/<CgroupPath>/<vmID>
	// if no value was provided, then /firecracker-containerd will be used as
	// the default value
	CgroupPath string `protobuf:"bytes,6,opt,name=CgroupPath,proto3" json:"CgroupPath,omitempty"`
	// DriveExposePolicy is used to configure the method to expose drive files.
	DriveExposePolicy    DriveExposePolicy `protobuf:"varint,7,opt,name=DriveExposePolicy,proto3,enum=DriveExposePolicy" json:"DriveExposePolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JailerConfig) Reset()         { *m = JailerConfig{} }
func (m *JailerConfig) String() string { return proto.CompactTextString(m) }
func (*JailerConfig) ProtoMessage()    {}
func (*JailerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{15}
}
func (m *JailerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JailerConfig.Unmarshal(m, b)
}
func (m *JailerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JailerConfig.Marshal(b, m, deterministic)
}
func (m *JailerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JailerConfig.Merge(m, src)
}
func (m *JailerConfig) XXX_Size() int {
	return xxx_messageInfo_JailerConfig.Size(m)
}
func (m *JailerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_JailerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_JailerConfig proto.InternalMessageInfo

func (m *JailerConfig) GetNetNS() string {
	if m != nil {
		return m.NetNS
	}
	return ""
}

func (m *JailerConfig) GetCPUs() string {
	if m != nil {
		return m.CPUs
	}
	return ""
}

func (m *JailerConfig) GetMems() string {
	if m != nil {
		return m.Mems
	}
	return ""
}

func (m *JailerConfig) GetUID() uint32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *JailerConfig) GetGID() uint32 {
	if m != nil {
		return m.GID
	}
	return 0
}

func (m *JailerConfig) GetCgroupPath() string {
	if m != nil {
		return m.CgroupPath
	}
	return ""
}

func (m *JailerConfig) GetDriveExposePolicy() DriveExposePolicy {
	if m != nil {
		return m.DriveExposePolicy
	}
	return DriveExposePolicy_COPY
}

type UpdateBalloonRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	AmountMib            int64    `protobuf:"varint,2,opt,name=AmountMib,proto3" json:"AmountMib,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBalloonRequest) Reset()         { *m = UpdateBalloonRequest{} }
func (m *UpdateBalloonRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBalloonRequest) ProtoMessage()    {}
func (*UpdateBalloonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{16}
}
func (m *UpdateBalloonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalloonRequest.Unmarshal(m, b)
}
func (m *UpdateBalloonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalloonRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBalloonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalloonRequest.Merge(m, src)
}
func (m *UpdateBalloonRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBalloonRequest.Size(m)
}
func (m *UpdateBalloonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalloonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalloonRequest proto.InternalMessageInfo

func (m *UpdateBalloonRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *UpdateBalloonRequest) GetAmountMib() int64 {
	if m != nil {
		return m.AmountMib
	}
	return 0
}

type GetBalloonConfigRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalloonConfigRequest) Reset()         { *m = GetBalloonConfigRequest{} }
func (m *GetBalloonConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalloonConfigRequest) ProtoMessage()    {}
func (*GetBalloonConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{17}
}
func (m *GetBalloonConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalloonConfigRequest.Unmarshal(m, b)
}
func (m *GetBalloonConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalloonConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetBalloonConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalloonConfigRequest.Merge(m, src)
}
func (m *GetBalloonConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalloonConfigRequest.Size(m)
}
func (m *GetBalloonConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalloonConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalloonConfigRequest proto.InternalMessageInfo

func (m *GetBalloonConfigRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type GetBalloonConfigResponse struct {
	BalloonConfig        *FirecrackerBalloonDevice `protobuf:"bytes,1,opt,name=BalloonConfig,proto3" json:"BalloonConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetBalloonConfigResponse) Reset()         { *m = GetBalloonConfigResponse{} }
func (m *GetBalloonConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalloonConfigResponse) ProtoMessage()    {}
func (*GetBalloonConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{18}
}
func (m *GetBalloonConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalloonConfigResponse.Unmarshal(m, b)
}
func (m *GetBalloonConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalloonConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetBalloonConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalloonConfigResponse.Merge(m, src)
}
func (m *GetBalloonConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalloonConfigResponse.Size(m)
}
func (m *GetBalloonConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalloonConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalloonConfigResponse proto.InternalMessageInfo

func (m *GetBalloonConfigResponse) GetBalloonConfig() *FirecrackerBalloonDevice {
	if m != nil {
		return m.BalloonConfig
	}
	return nil
}

type GetBalloonStatsRequest struct {
	VMID                 string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalloonStatsRequest) Reset()         { *m = GetBalloonStatsRequest{} }
func (m *GetBalloonStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalloonStatsRequest) ProtoMessage()    {}
func (*GetBalloonStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{19}
}
func (m *GetBalloonStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalloonStatsRequest.Unmarshal(m, b)
}
func (m *GetBalloonStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalloonStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetBalloonStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalloonStatsRequest.Merge(m, src)
}
func (m *GetBalloonStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalloonStatsRequest.Size(m)
}
func (m *GetBalloonStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalloonStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalloonStatsRequest proto.InternalMessageInfo

func (m *GetBalloonStatsRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

type GetBalloonStatsResponse struct {
	// Actual amount of memory (in MiB) the device is holding.
	ActualMib int64 `protobuf:"varint,1,opt,name=ActualMib,proto3" json:"ActualMib,omitempty"`
	// Actual number of pages the device is holding.
	ActualPages int64 `protobuf:"varint,2,opt,name=ActualPages,proto3" json:"ActualPages,omitempty"`
	// An estimate of how much memory is available (in bytes) for starting new applications, without pushing the system to swap.
	AvailableMemory int64 `protobuf:"varint,3,opt,name=AvailableMemory,proto3" json:"AvailableMemory,omitempty"`
	// The amount of memory, in bytes, that can be quickly reclaimed without additional I/O.
	// Typically these pages are used for caching files from disk.
	DiskCaches int64 `protobuf:"varint,4,opt,name=DiskCaches,proto3" json:"DiskCaches,omitempty"`
	// The amount of memory not being used for any purpose (in bytes).
	FreeMemory int64 `protobuf:"varint,5,opt,name=FreeMemory,proto3" json:"FreeMemory,omitempty"`
	// The number of successful hugetlb page allocations in the guest.
	HugetlbAllocations int64 `protobuf:"varint,6,opt,name=HugetlbAllocations,proto3" json:"HugetlbAllocations,omitempty"`
	// The number of failed hugetlb page allocations in the guest.
	HugetlbFailures int64 `protobuf:"varint,7,opt,name=HugetlbFailures,proto3" json:"HugetlbFailures,omitempty"`
	// The number of major page faults that have occurred.
	MajorFaults int64 `protobuf:"varint,8,opt,name=MajorFaults,proto3" json:"MajorFaults,omitempty"`
	// The number of minor page faults that have occurred.
	MinorFaults int64 `protobuf:"varint,9,opt,name=MinorFaults,proto3" json:"MinorFaults,omitempty"`
	// The amount of memory that has been swapped in (in bytes).
	SwapIn int64 `protobuf:"varint,10,opt,name=SwapIn,proto3" json:"SwapIn,omitempty"`
	// The amount of memory that has been swapped out to disk (in bytes).
	SwapOut int64 `protobuf:"varint,11,opt,name=SwapOut,proto3" json:"SwapOut,omitempty"`
	// Target amount of memory (in MiB) the device aims to hold.
	TargetMib int64 `protobuf:"varint,12,opt,name=TargetMib,proto3" json:"TargetMib,omitempty"`
	// Target number of pages the device aims to hold.
	TargetPages int64 `protobuf:"varint,13,opt,name=TargetPages,proto3" json:"TargetPages,omitempty"`
	// The total amount of memory available (in bytes).
	TotalMemory          int64    `protobuf:"varint,14,opt,name=TotalMemory,proto3" json:"TotalMemory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalloonStatsResponse) Reset()         { *m = GetBalloonStatsResponse{} }
func (m *GetBalloonStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalloonStatsResponse) ProtoMessage()    {}
func (*GetBalloonStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{20}
}
func (m *GetBalloonStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalloonStatsResponse.Unmarshal(m, b)
}
func (m *GetBalloonStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalloonStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetBalloonStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalloonStatsResponse.Merge(m, src)
}
func (m *GetBalloonStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalloonStatsResponse.Size(m)
}
func (m *GetBalloonStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalloonStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalloonStatsResponse proto.InternalMessageInfo

func (m *GetBalloonStatsResponse) GetActualMib() int64 {
	if m != nil {
		return m.ActualMib
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetActualPages() int64 {
	if m != nil {
		return m.ActualPages
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetAvailableMemory() int64 {
	if m != nil {
		return m.AvailableMemory
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetDiskCaches() int64 {
	if m != nil {
		return m.DiskCaches
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetFreeMemory() int64 {
	if m != nil {
		return m.FreeMemory
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetHugetlbAllocations() int64 {
	if m != nil {
		return m.HugetlbAllocations
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetHugetlbFailures() int64 {
	if m != nil {
		return m.HugetlbFailures
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetMajorFaults() int64 {
	if m != nil {
		return m.MajorFaults
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetMinorFaults() int64 {
	if m != nil {
		return m.MinorFaults
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetSwapIn() int64 {
	if m != nil {
		return m.SwapIn
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetSwapOut() int64 {
	if m != nil {
		return m.SwapOut
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetTargetMib() int64 {
	if m != nil {
		return m.TargetMib
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetTargetPages() int64 {
	if m != nil {
		return m.TargetPages
	}
	return 0
}

func (m *GetBalloonStatsResponse) GetTotalMemory() int64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

type UpdateBalloonStatsRequest struct {
	VMID                  string   `protobuf:"bytes,1,opt,name=VMID,proto3" json:"VMID,omitempty"`
	StatsPollingIntervals int64    `protobuf:"varint,2,opt,name=StatsPollingIntervals,proto3" json:"StatsPollingIntervals,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *UpdateBalloonStatsRequest) Reset()         { *m = UpdateBalloonStatsRequest{} }
func (m *UpdateBalloonStatsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBalloonStatsRequest) ProtoMessage()    {}
func (*UpdateBalloonStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73317e9fb8da571, []int{21}
}
func (m *UpdateBalloonStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalloonStatsRequest.Unmarshal(m, b)
}
func (m *UpdateBalloonStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalloonStatsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBalloonStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalloonStatsRequest.Merge(m, src)
}
func (m *UpdateBalloonStatsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBalloonStatsRequest.Size(m)
}
func (m *UpdateBalloonStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalloonStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalloonStatsRequest proto.InternalMessageInfo

func (m *UpdateBalloonStatsRequest) GetVMID() string {
	if m != nil {
		return m.VMID
	}
	return ""
}

func (m *UpdateBalloonStatsRequest) GetStatsPollingIntervals() int64 {
	if m != nil {
		return m.StatsPollingIntervals
	}
	return 0
}

func init() {
	proto.RegisterEnum("DriveExposePolicy", DriveExposePolicy_name, DriveExposePolicy_value)
	proto.RegisterType((*CreateVMRequest)(nil), "CreateVMRequest")
	proto.RegisterType((*CreateVMResponse)(nil), "CreateVMResponse")
	proto.RegisterType((*PauseVMRequest)(nil), "PauseVMRequest")
	proto.RegisterType((*ResumeVMRequest)(nil), "ResumeVMRequest")
	proto.RegisterType((*StopVMRequest)(nil), "StopVMRequest")
	proto.RegisterType((*GetVMInfoRequest)(nil), "GetVMInfoRequest")
	proto.RegisterType((*GetVMInfoResponse)(nil), "GetVMInfoResponse")
	proto.RegisterType((*SetVMMetadataRequest)(nil), "SetVMMetadataRequest")
	proto.RegisterType((*UpdateVMMetadataRequest)(nil), "UpdateVMMetadataRequest")
	proto.RegisterType((*GetVMMetadataRequest)(nil), "GetVMMetadataRequest")
	proto.RegisterType((*GetVMMetadataResponse)(nil), "GetVMMetadataResponse")
	proto.RegisterType((*CreateSnapshotRequest)(nil), "CreateSnapshotRequest")
	proto.RegisterType((*LoadSnapshotRequest)(nil), "LoadSnapshotRequest")
	proto.RegisterType((*LoadResponse)(nil), "LoadResponse")
	proto.RegisterType((*OffloadRequest)(nil), "OffloadRequest")
	proto.RegisterType((*JailerConfig)(nil), "JailerConfig")
	proto.RegisterType((*UpdateBalloonRequest)(nil), "UpdateBalloonRequest")
	proto.RegisterType((*GetBalloonConfigRequest)(nil), "GetBalloonConfigRequest")
	proto.RegisterType((*GetBalloonConfigResponse)(nil), "GetBalloonConfigResponse")
	proto.RegisterType((*GetBalloonStatsRequest)(nil), "GetBalloonStatsRequest")
	proto.RegisterType((*GetBalloonStatsResponse)(nil), "GetBalloonStatsResponse")
	proto.RegisterType((*UpdateBalloonStatsRequest)(nil), "UpdateBalloonStatsRequest")
}

func init() { proto.RegisterFile("firecracker.proto", fileDescriptor_a73317e9fb8da571) }

var fileDescriptor_a73317e9fb8da571 = []byte{
	// 1112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0x9f, 0xaa, 0x38, 0x7f, 0xce, 0x71, 0xe2, 0x70, 0x49, 0xab, 0x16, 0x45, 0x61, 0x08, 0x5b,
	0x67, 0x04, 0x5b, 0x80, 0x25, 0xc3, 0x30, 0xec, 0x65, 0x75, 0xec, 0x38, 0x75, 0x5b, 0x25, 0x06,
	0x9d, 0x04, 0xd8, 0xf6, 0xc4, 0x28, 0x67, 0x47, 0x0b, 0x2d, 0x7a, 0x22, 0x95, 0x36, 0x9f, 0x6b,
	0x1f, 0x62, 0xef, 0xfb, 0x0c, 0xfb, 0x0a, 0x7b, 0xdb, 0xc3, 0x40, 0x4a, 0xb6, 0x64, 0xd9, 0x71,
	0x03, 0x0c, 0x18, 0xb0, 0x27, 0x93, 0xbf, 0xfb, 0x91, 0x77, 0xfc, 0xdd, 0x51, 0x47, 0xc3, 0x56,
	0x3f, 0x88, 0xd0, 0x8f, 0x98, 0x7f, 0x83, 0xd1, 0xde, 0x28, 0x12, 0x4a, 0x3c, 0x2b, 0xab, 0xbb,
	0x11, 0xca, 0x64, 0xe2, 0xfe, 0x59, 0x82, 0xcd, 0x66, 0x84, 0x4c, 0xe1, 0x85, 0x47, 0xf1, 0xd7,
	0x18, 0xa5, 0x22, 0x04, 0x96, 0x2e, 0xbc, 0x4e, 0xcb, 0xb1, 0x6a, 0x56, 0x7d, 0x8d, 0x9a, 0x31,
	0x79, 0x05, 0xe0, 0x31, 0xff, 0x3a, 0x08, 0xb1, 0xd9, 0x1f, 0x38, 0x8f, 0x6a, 0x56, 0xbd, 0xbc,
	0x5f, 0xdb, 0x6b, 0x67, 0x9b, 0x8f, 0xad, 0x22, 0xec, 0x07, 0x83, 0x38, 0x62, 0x2a, 0x10, 0x21,
	0xcd, 0xad, 0x21, 0x75, 0xd8, 0x7c, 0x8b, 0x51, 0x88, 0xbc, 0x33, 0x64, 0x03, 0xec, 0x32, 0x75,
	0xed, 0xd8, 0xc6, 0x41, 0x11, 0x26, 0x2f, 0x00, 0x12, 0xa8, 0x11, 0x0d, 0xa4, 0xb3, 0x64, 0x48,
	0x39, 0x84, 0x1c, 0xc0, 0x1a, 0x15, 0x42, 0xb5, 0xa2, 0xe0, 0x16, 0x9d, 0x92, 0x09, 0x65, 0x27,
	0x1f, 0xca, 0xc4, 0x48, 0x33, 0x1e, 0xf9, 0x0e, 0xca, 0x66, 0xe0, 0x89, 0x38, 0x54, 0xd2, 0x59,
	0xae, 0xd9, 0xf5, 0xf2, 0xfe, 0xe3, 0xfc, 0xb2, 0xcc, 0x4c, 0xf3, 0x54, 0xf2, 0x06, 0xb6, 0x4e,
	0x50, 0xbd, 0x17, 0xd1, 0x4d, 0x27, 0x54, 0x18, 0xf5, 0x99, 0x8f, 0xd2, 0x59, 0x31, 0xeb, 0x9f,
	0xe7, 0xd7, 0x17, 0x49, 0x74, 0x76, 0x19, 0x79, 0x09, 0x1b, 0x4d, 0x11, 0x2a, 0x16, 0x84, 0x18,
	0x35, 0xf5, 0xf6, 0xce, 0x6a, 0xcd, 0xaa, 0x97, 0x68, 0x01, 0x25, 0xdf, 0x83, 0x73, 0xf4, 0x21,
	0x50, 0x8d, 0xbe, 0xc2, 0xa8, 0xc1, 0xf9, 0x19, 0x93, 0x37, 0xb2, 0x85, 0x1c, 0x15, 0x5e, 0x39,
	0x6b, 0x35, 0xab, 0xbe, 0x4a, 0xef, 0xb5, 0x93, 0xaf, 0x61, 0xfd, 0x0d, 0x0b, 0xb8, 0xde, 0x4a,
	0xe7, 0xc2, 0x01, 0xa3, 0x50, 0x65, 0x2f, 0x0f, 0xd2, 0x29, 0x8a, 0x0e, 0xeb, 0x2c, 0x18, 0xa2,
	0x88, 0x55, 0x0f, 0x7d, 0x11, 0x5e, 0x49, 0xa7, 0x5c, 0xb3, 0xea, 0x15, 0x5a, 0x40, 0x49, 0x0d,
	0xca, 0xef, 0xc4, 0xa0, 0x1d, 0xf4, 0x85, 0xc9, 0xdf, 0xba, 0x49, 0x4d, 0x1e, 0xd2, 0x59, 0xf6,
	0x50, 0x45, 0x81, 0x2f, 0x27, 0xac, 0x4a, 0x92, 0xe5, 0x02, 0x4c, 0x7e, 0x80, 0xca, 0x21, 0xe3,
	0x5c, 0x88, 0xb0, 0x85, 0xb7, 0x81, 0x8f, 0xce, 0x86, 0x89, 0xf3, 0x69, 0x5e, 0xd2, 0x29, 0x02,
	0x9d, 0xe6, 0x93, 0x5d, 0xa8, 0xa6, 0x02, 0x9f, 0xb0, 0x21, 0xca, 0x11, 0xf3, 0xd1, 0xd9, 0x34,
	0xbe, 0x66, 0x70, 0xf7, 0x6f, 0x0b, 0xaa, 0x59, 0x99, 0xcb, 0x91, 0x08, 0x25, 0xce, 0xad, 0xf3,
	0x17, 0x00, 0x3d, 0xe1, 0xdf, 0xa0, 0x32, 0xa1, 0x3f, 0x4a, 0x6a, 0x2f, 0x43, 0x8a, 0x0a, 0xd8,
	0x0f, 0x52, 0x60, 0x69, 0xbe, 0x02, 0x2f, 0x00, 0x9a, 0x83, 0x48, 0xc4, 0x23, 0x43, 0x2a, 0x25,
	0xbe, 0x32, 0x44, 0xfb, 0x3a, 0xef, 0xb6, 0xb5, 0x73, 0x43, 0x58, 0x4e, 0x7c, 0xe5, 0x20, 0x9d,
	0xb7, 0x9c, 0x5a, 0xdd, 0x4e, 0xcb, 0x59, 0x31, 0xa4, 0x02, 0xea, 0x7e, 0x06, 0x1b, 0x5d, 0x16,
	0xcb, 0xc5, 0x77, 0xdc, 0xfd, 0x1c, 0x36, 0x29, 0xca, 0x78, 0xf8, 0x11, 0xda, 0x5b, 0xa8, 0xf4,
	0x94, 0x18, 0x2d, 0xfe, 0x5e, 0xcc, 0x56, 0xd4, 0xa3, 0x79, 0x15, 0xe5, 0xbe, 0x84, 0xea, 0x31,
	0xaa, 0x0b, 0xaf, 0x13, 0xf6, 0xc5, 0x22, 0xa7, 0xbf, 0x59, 0xb0, 0x95, 0x23, 0xfe, 0x3f, 0x32,
	0xe8, 0xb6, 0x61, 0xbb, 0xa7, 0x83, 0xf6, 0x50, 0xb1, 0x2b, 0xa6, 0xd8, 0x22, 0xc5, 0x9e, 0xc1,
	0xea, 0x98, 0x96, 0x46, 0x3d, 0x99, 0xbb, 0x1d, 0x78, 0x72, 0x3e, 0xba, 0x32, 0xd5, 0xfb, 0x6f,
	0xb7, 0xda, 0x85, 0xed, 0xe3, 0x07, 0x86, 0xe4, 0x1e, 0xc0, 0x4e, 0x81, 0x9b, 0xea, 0x9e, 0x77,
	0x60, 0x15, 0x1c, 0xdc, 0xc1, 0x4e, 0x72, 0xd3, 0x7a, 0x21, 0x1b, 0xc9, 0x6b, 0xa1, 0x16, 0x45,
	0xba, 0x0b, 0xd5, 0x31, 0xad, 0x1d, 0x70, 0xcc, 0xa5, 0x6c, 0x06, 0xd7, 0x89, 0xf3, 0x70, 0x38,
	0xa1, 0xa5, 0x89, 0xcb, 0x41, 0xee, 0xef, 0x16, 0x7c, 0xfa, 0x4e, 0xb0, 0xab, 0xff, 0xdc, 0x33,
	0x71, 0x61, 0xfd, 0x28, 0x64, 0x97, 0x1c, 0xcf, 0x25, 0x46, 0xdd, 0xb6, 0xa9, 0x97, 0x55, 0x3a,
	0x85, 0xcd, 0xfd, 0x5e, 0x95, 0xee, 0xf9, 0x5e, 0x7d, 0x0b, 0xeb, 0xfa, 0x20, 0x13, 0xc1, 0x67,
	0x2f, 0xba, 0x75, 0xdf, 0x45, 0x3f, 0xed, 0xf7, 0xb9, 0x59, 0x7a, 0x7f, 0x5e, 0xff, 0xb0, 0xa6,
	0x5b, 0x04, 0xd9, 0x86, 0xd2, 0x09, 0xaa, 0x93, 0x5e, 0xca, 0x4a, 0x26, 0x7a, 0x69, 0xb3, 0x7b,
	0x2e, 0x53, 0x59, 0xcc, 0x58, 0x63, 0x1e, 0x0e, 0x65, 0xaa, 0x81, 0x19, 0x93, 0x2a, 0xd8, 0xe7,
	0x9d, 0x96, 0x39, 0x73, 0x85, 0xea, 0xa1, 0x46, 0x8e, 0x3b, 0x2d, 0x73, 0xba, 0x0a, 0xd5, 0xc3,
	0xc2, 0x4d, 0x59, 0x9e, 0xf9, 0xd6, 0xbd, 0x82, 0x2d, 0xd3, 0x73, 0x8f, 0x3e, 0x8c, 0x84, 0xc4,
	0xae, 0xe0, 0x81, 0x7f, 0x67, 0x3e, 0x66, 0x1b, 0xfb, 0x64, 0x6f, 0xc6, 0x42, 0x67, 0xc9, 0xee,
	0x6b, 0xd8, 0x4e, 0xee, 0x48, 0xda, 0x25, 0x16, 0x25, 0xff, 0x39, 0xac, 0x35, 0x86, 0xba, 0xd1,
	0x7a, 0xc1, 0xa5, 0x39, 0x9e, 0x4d, 0x33, 0xc0, 0xfd, 0x0a, 0x9e, 0x1c, 0xa3, 0x4a, 0xb7, 0x49,
	0xfb, 0xe5, 0x02, 0x35, 0x7f, 0x06, 0x67, 0x96, 0x9e, 0xe6, 0x2d, 0x6b, 0x72, 0x69, 0x33, 0xb6,
	0x1e, 0xda, 0xe4, 0x12, 0xbe, 0xfb, 0x25, 0x3c, 0xce, 0x36, 0xef, 0x29, 0xa6, 0xe4, 0xa2, 0x50,
	0xfe, 0xb2, 0xf3, 0xa1, 0xa7, 0xf4, 0x34, 0x14, 0x7d, 0x66, 0x5f, 0xc5, 0x8c, 0xeb, 0x33, 0x5b,
	0xe9, 0x99, 0xc7, 0x80, 0x2e, 0xf1, 0x64, 0xd2, 0x65, 0x03, 0x94, 0xa9, 0x26, 0x79, 0x48, 0x7f,
	0x15, 0x1b, 0xb7, 0x2c, 0xe0, 0xba, 0xa2, 0x3d, 0x1c, 0x8a, 0xe8, 0xce, 0x14, 0x81, 0x4d, 0x8b,
	0xb0, 0xce, 0x75, 0x2b, 0x90, 0x37, 0x4d, 0xe6, 0x5f, 0x63, 0xf2, 0x7e, 0xb3, 0x69, 0x0e, 0xd1,
	0xf6, 0x76, 0x84, 0xe3, 0x4d, 0x4a, 0x89, 0x3d, 0x43, 0xc8, 0x1e, 0x90, 0xd7, 0xf1, 0x00, 0x15,
	0xbf, 0x6c, 0x70, 0x2e, 0x7c, 0xf3, 0x94, 0x94, 0xa6, 0x66, 0x6c, 0x3a, 0xc7, 0xa2, 0x23, 0x4b,
	0xd1, 0x36, 0x0b, 0x78, 0x1c, 0x99, 0xe7, 0x99, 0x89, 0xac, 0x00, 0x9b, 0x8b, 0xcc, 0x7e, 0x11,
	0x51, 0x9b, 0xc5, 0x5c, 0x49, 0xf3, 0xf6, 0xb2, 0x69, 0x1e, 0x32, 0x8c, 0x20, 0x9c, 0x30, 0xd6,
	0x52, 0x46, 0x06, 0x91, 0xc7, 0xb0, 0xdc, 0x7b, 0xcf, 0x46, 0x9d, 0xd0, 0x3c, 0xac, 0x6c, 0x9a,
	0xce, 0x88, 0x03, 0x2b, 0x7a, 0x74, 0x1a, 0x2b, 0xf3, 0x78, 0xb2, 0xe9, 0x78, 0xaa, 0x95, 0x3f,
	0x63, 0xd1, 0x00, 0x4d, 0xb5, 0xad, 0x27, 0xca, 0x4f, 0x00, 0xed, 0x31, 0x99, 0x24, 0xca, 0x57,
	0x12, 0x8f, 0x39, 0xc8, 0x30, 0x84, 0x62, 0x3c, 0x15, 0x6c, 0x23, 0x65, 0x64, 0x90, 0x8b, 0xf0,
	0x74, 0xaa, 0xf6, 0x3f, 0x56, 0x28, 0xe4, 0x1b, 0xd8, 0x31, 0x9c, 0xae, 0xe0, 0x3c, 0x08, 0x07,
	0xe6, 0x85, 0x7a, 0xcb, 0xf8, 0x38, 0xf1, 0xf3, 0x8d, 0xbb, 0x5f, 0xcc, 0xb9, 0xa4, 0x64, 0x15,
	0x96, 0x9a, 0xa7, 0xdd, 0x1f, 0xab, 0x9f, 0xe8, 0xd1, 0x61, 0xe7, 0xa4, 0x55, 0xb5, 0x0e, 0x57,
	0x7e, 0x2a, 0x99, 0xbf, 0x17, 0x97, 0xcb, 0xe6, 0xe7, 0xe0, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x78, 0x5e, 0x86, 0x80, 0x87, 0x0c, 0x00, 0x00,
}
