// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Message to store bundle/config.json bytes
type ExtraData struct {
	JsonSpec             []byte     `protobuf:"bytes,1,opt,name=JsonSpec,proto3" json:"JsonSpec,omitempty"`
	RuncOptions          *types.Any `protobuf:"bytes,2,opt,name=RuncOptions,proto3" json:"RuncOptions,omitempty"`
	StdinPort            uint32     `protobuf:"varint,3,opt,name=StdinPort,proto3" json:"StdinPort,omitempty"`
	StdoutPort           uint32     `protobuf:"varint,4,opt,name=StdoutPort,proto3" json:"StdoutPort,omitempty"`
	StderrPort           uint32     `protobuf:"varint,5,opt,name=StderrPort,proto3" json:"StderrPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExtraData) Reset()         { *m = ExtraData{} }
func (m *ExtraData) String() string { return proto.CompactTextString(m) }
func (*ExtraData) ProtoMessage()    {}
func (*ExtraData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}
func (m *ExtraData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraData.Unmarshal(m, b)
}
func (m *ExtraData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraData.Marshal(b, m, deterministic)
}
func (m *ExtraData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraData.Merge(m, src)
}
func (m *ExtraData) XXX_Size() int {
	return xxx_messageInfo_ExtraData.Size(m)
}
func (m *ExtraData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraData.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraData proto.InternalMessageInfo

func (m *ExtraData) GetJsonSpec() []byte {
	if m != nil {
		return m.JsonSpec
	}
	return nil
}

func (m *ExtraData) GetRuncOptions() *types.Any {
	if m != nil {
		return m.RuncOptions
	}
	return nil
}

func (m *ExtraData) GetStdinPort() uint32 {
	if m != nil {
		return m.StdinPort
	}
	return 0
}

func (m *ExtraData) GetStdoutPort() uint32 {
	if m != nil {
		return m.StdoutPort
	}
	return 0
}

func (m *ExtraData) GetStderrPort() uint32 {
	if m != nil {
		return m.StderrPort
	}
	return 0
}

// Message to specify network config for a Firecracker VM
type FirecrackerNetworkInterface struct {
	AllowMMDS      bool                    `protobuf:"varint,1,opt,name=AllowMMDS,proto3" json:"AllowMMDS,omitempty"`
	InRateLimiter  *FirecrackerRateLimiter `protobuf:"bytes,2,opt,name=InRateLimiter,proto3" json:"InRateLimiter,omitempty"`
	OutRateLimiter *FirecrackerRateLimiter `protobuf:"bytes,3,opt,name=OutRateLimiter,proto3" json:"OutRateLimiter,omitempty"`
	// CNIConfiguration specifies CNI configuration that will be used to generate
	// a network interface for a Firecracker VM.
	CNIConfig *CNIConfiguration `protobuf:"bytes,4,opt,name=CNIConfig,proto3" json:"CNIConfig,omitempty"`
	// StaticNetworkConfiguration specifies static configuration parameters for a
	// Firecracker VM's network interface
	StaticConfig         *StaticNetworkConfiguration `protobuf:"bytes,5,opt,name=StaticConfig,proto3" json:"StaticConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FirecrackerNetworkInterface) Reset()         { *m = FirecrackerNetworkInterface{} }
func (m *FirecrackerNetworkInterface) String() string { return proto.CompactTextString(m) }
func (*FirecrackerNetworkInterface) ProtoMessage()    {}
func (*FirecrackerNetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}
func (m *FirecrackerNetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerNetworkInterface.Unmarshal(m, b)
}
func (m *FirecrackerNetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerNetworkInterface.Marshal(b, m, deterministic)
}
func (m *FirecrackerNetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerNetworkInterface.Merge(m, src)
}
func (m *FirecrackerNetworkInterface) XXX_Size() int {
	return xxx_messageInfo_FirecrackerNetworkInterface.Size(m)
}
func (m *FirecrackerNetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerNetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerNetworkInterface proto.InternalMessageInfo

func (m *FirecrackerNetworkInterface) GetAllowMMDS() bool {
	if m != nil {
		return m.AllowMMDS
	}
	return false
}

func (m *FirecrackerNetworkInterface) GetInRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.InRateLimiter
	}
	return nil
}

func (m *FirecrackerNetworkInterface) GetOutRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.OutRateLimiter
	}
	return nil
}

func (m *FirecrackerNetworkInterface) GetCNIConfig() *CNIConfiguration {
	if m != nil {
		return m.CNIConfig
	}
	return nil
}

func (m *FirecrackerNetworkInterface) GetStaticConfig() *StaticNetworkConfiguration {
	if m != nil {
		return m.StaticConfig
	}
	return nil
}

// Message to specify CNI configuration that will be used to
// generate a network interface for a Firecracker VM
type CNIConfiguration struct {
	// NetworkName is the name of a CNI network (as found in CNI
	// configuration files) that will be used to generate the
	// network interface.
	NetworkName string `protobuf:"bytes,1,opt,name=NetworkName,proto3" json:"NetworkName,omitempty"`
	// InterfaceName corresponds to the CNI_IFNAME parameter that will be
	// provided to CNI plugins during invocation.
	InterfaceName string `protobuf:"bytes,2,opt,name=InterfaceName,proto3" json:"InterfaceName,omitempty"`
	// BinPath is a list of directories that will be searched when
	// looking for CNI plugin binaries. Defaults to just "/opt/cni/bin"
	BinPath []string `protobuf:"bytes,3,rep,name=BinPath,proto3" json:"BinPath,omitempty"`
	// ConfDir is the directory in which CNI configuration will be sought.
	// If not specified, will default to "/etc/cni/conf.d".
	ConfDir string `protobuf:"bytes,4,opt,name=ConfDir,proto3" json:"ConfDir,omitempty"`
	// CacheDir is the directory in which CNI results will be temporarily
	// cached by the runtime. If not specified, it will default to
	// "/var/lib/cni"
	CacheDir string `protobuf:"bytes,5,opt,name=CacheDir,proto3" json:"CacheDir,omitempty"`
	// Args corresponds to the CNI_ARGS parameter that will be provided to
	// CNI plugins on invocation.
	Args                 []*CNIConfiguration_CNIArg `protobuf:"bytes,6,rep,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CNIConfiguration) Reset()         { *m = CNIConfiguration{} }
func (m *CNIConfiguration) String() string { return proto.CompactTextString(m) }
func (*CNIConfiguration) ProtoMessage()    {}
func (*CNIConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}
func (m *CNIConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIConfiguration.Unmarshal(m, b)
}
func (m *CNIConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIConfiguration.Marshal(b, m, deterministic)
}
func (m *CNIConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIConfiguration.Merge(m, src)
}
func (m *CNIConfiguration) XXX_Size() int {
	return xxx_messageInfo_CNIConfiguration.Size(m)
}
func (m *CNIConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_CNIConfiguration proto.InternalMessageInfo

func (m *CNIConfiguration) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

func (m *CNIConfiguration) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *CNIConfiguration) GetBinPath() []string {
	if m != nil {
		return m.BinPath
	}
	return nil
}

func (m *CNIConfiguration) GetConfDir() string {
	if m != nil {
		return m.ConfDir
	}
	return ""
}

func (m *CNIConfiguration) GetCacheDir() string {
	if m != nil {
		return m.CacheDir
	}
	return ""
}

func (m *CNIConfiguration) GetArgs() []*CNIConfiguration_CNIArg {
	if m != nil {
		return m.Args
	}
	return nil
}

type CNIConfiguration_CNIArg struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNIConfiguration_CNIArg) Reset()         { *m = CNIConfiguration_CNIArg{} }
func (m *CNIConfiguration_CNIArg) String() string { return proto.CompactTextString(m) }
func (*CNIConfiguration_CNIArg) ProtoMessage()    {}
func (*CNIConfiguration_CNIArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2, 0}
}
func (m *CNIConfiguration_CNIArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIConfiguration_CNIArg.Unmarshal(m, b)
}
func (m *CNIConfiguration_CNIArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIConfiguration_CNIArg.Marshal(b, m, deterministic)
}
func (m *CNIConfiguration_CNIArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIConfiguration_CNIArg.Merge(m, src)
}
func (m *CNIConfiguration_CNIArg) XXX_Size() int {
	return xxx_messageInfo_CNIConfiguration_CNIArg.Size(m)
}
func (m *CNIConfiguration_CNIArg) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIConfiguration_CNIArg.DiscardUnknown(m)
}

var xxx_messageInfo_CNIConfiguration_CNIArg proto.InternalMessageInfo

func (m *CNIConfiguration_CNIArg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CNIConfiguration_CNIArg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Message to specify static configuration parameters for a
// Firecracker VM's network interface
type StaticNetworkConfiguration struct {
	MacAddress  string `protobuf:"bytes,1,opt,name=MacAddress,proto3" json:"MacAddress,omitempty"`
	HostDevName string `protobuf:"bytes,2,opt,name=HostDevName,proto3" json:"HostDevName,omitempty"`
	// IPConfig optionally provides static IP configuration that will be configured
	// on the VM's internal networking interface. If not specified, no IP
	// configuration will be applied to the VM's internal nic automatically.
	IPConfig             *IPConfiguration `protobuf:"bytes,3,opt,name=IPConfig,proto3" json:"IPConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StaticNetworkConfiguration) Reset()         { *m = StaticNetworkConfiguration{} }
func (m *StaticNetworkConfiguration) String() string { return proto.CompactTextString(m) }
func (*StaticNetworkConfiguration) ProtoMessage()    {}
func (*StaticNetworkConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}
func (m *StaticNetworkConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticNetworkConfiguration.Unmarshal(m, b)
}
func (m *StaticNetworkConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticNetworkConfiguration.Marshal(b, m, deterministic)
}
func (m *StaticNetworkConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticNetworkConfiguration.Merge(m, src)
}
func (m *StaticNetworkConfiguration) XXX_Size() int {
	return xxx_messageInfo_StaticNetworkConfiguration.Size(m)
}
func (m *StaticNetworkConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticNetworkConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_StaticNetworkConfiguration proto.InternalMessageInfo

func (m *StaticNetworkConfiguration) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *StaticNetworkConfiguration) GetHostDevName() string {
	if m != nil {
		return m.HostDevName
	}
	return ""
}

func (m *StaticNetworkConfiguration) GetIPConfig() *IPConfiguration {
	if m != nil {
		return m.IPConfig
	}
	return nil
}

// Message to specify static IP configuration that will be
// applied to a Firecracker VM's network interface internally
type IPConfiguration struct {
	// PrimaryAddr specifies, in CIDR notation, the primary address
	// and subnet that a network interface will be assigned inside
	// the VM.
	PrimaryAddr string `protobuf:"bytes,1,opt,name=PrimaryAddr,proto3" json:"PrimaryAddr,omitempty"`
	// GatewayAddr specifies the default gateway that a network interface
	// should use inside the VM.
	GatewayAddr string `protobuf:"bytes,3,opt,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
	// Nameservers is a list of nameservers that the VM will be configured
	// to use internally. Currently only up to 2 nameservers can be specified
	// (any more in the list will be ignored) and configuration is provided
	// to the VM via /proc/net/pnp.
	Nameservers          []string `protobuf:"bytes,4,rep,name=Nameservers,proto3" json:"Nameservers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPConfiguration) Reset()         { *m = IPConfiguration{} }
func (m *IPConfiguration) String() string { return proto.CompactTextString(m) }
func (*IPConfiguration) ProtoMessage()    {}
func (*IPConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}
func (m *IPConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPConfiguration.Unmarshal(m, b)
}
func (m *IPConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPConfiguration.Marshal(b, m, deterministic)
}
func (m *IPConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPConfiguration.Merge(m, src)
}
func (m *IPConfiguration) XXX_Size() int {
	return xxx_messageInfo_IPConfiguration.Size(m)
}
func (m *IPConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_IPConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_IPConfiguration proto.InternalMessageInfo

func (m *IPConfiguration) GetPrimaryAddr() string {
	if m != nil {
		return m.PrimaryAddr
	}
	return ""
}

func (m *IPConfiguration) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

func (m *IPConfiguration) GetNameservers() []string {
	if m != nil {
		return m.Nameservers
	}
	return nil
}

// Message to set the machine config for a Firecracker VM
type FirecrackerMachineConfiguration struct {
	CPUTemplate string `protobuf:"bytes,1,opt,name=CPUTemplate,proto3" json:"CPUTemplate,omitempty"`
	HtEnabled   bool   `protobuf:"varint,2,opt,name=HtEnabled,proto3" json:"HtEnabled,omitempty"`
	// Specifies the memory size of VM
	// This lets us create a Firecracker VM of up to 4096 TiB, which
	// for a microVM should be large enough
	MemSizeMib           uint32   `protobuf:"varint,3,opt,name=MemSizeMib,proto3" json:"MemSizeMib,omitempty"`
	VcpuCount            uint32   `protobuf:"varint,4,opt,name=VcpuCount,proto3" json:"VcpuCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirecrackerMachineConfiguration) Reset()         { *m = FirecrackerMachineConfiguration{} }
func (m *FirecrackerMachineConfiguration) String() string { return proto.CompactTextString(m) }
func (*FirecrackerMachineConfiguration) ProtoMessage()    {}
func (*FirecrackerMachineConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}
func (m *FirecrackerMachineConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerMachineConfiguration.Unmarshal(m, b)
}
func (m *FirecrackerMachineConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerMachineConfiguration.Marshal(b, m, deterministic)
}
func (m *FirecrackerMachineConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerMachineConfiguration.Merge(m, src)
}
func (m *FirecrackerMachineConfiguration) XXX_Size() int {
	return xxx_messageInfo_FirecrackerMachineConfiguration.Size(m)
}
func (m *FirecrackerMachineConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerMachineConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerMachineConfiguration proto.InternalMessageInfo

func (m *FirecrackerMachineConfiguration) GetCPUTemplate() string {
	if m != nil {
		return m.CPUTemplate
	}
	return ""
}

func (m *FirecrackerMachineConfiguration) GetHtEnabled() bool {
	if m != nil {
		return m.HtEnabled
	}
	return false
}

func (m *FirecrackerMachineConfiguration) GetMemSizeMib() uint32 {
	if m != nil {
		return m.MemSizeMib
	}
	return 0
}

func (m *FirecrackerMachineConfiguration) GetVcpuCount() uint32 {
	if m != nil {
		return m.VcpuCount
	}
	return 0
}

// Message to specify the block device config for a Firecracker VM
type FirecrackerRootDrive struct {
	// (Required) HostPath is the path on the host to the filesystem image or device
	// that will supply the rootfs of the VM.
	HostPath string `protobuf:"bytes,1,opt,name=HostPath,proto3" json:"HostPath,omitempty"`
	// (Optional) If the HostPath points to a drive or image with multiple
	// partitions, Partuuid specifies which partition will be used to boot
	// the VM
	Partuuid string `protobuf:"bytes,2,opt,name=Partuuid,proto3" json:"Partuuid,omitempty"`
	// (Optional) If set to true, IsWritable results in the VM Guest's rootfs
	// being mounted as read-write. Defaults to false, in which case the
	// rootfs is mounted as read-only.
	IsWritable bool `protobuf:"varint,3,opt,name=IsWritable,proto3" json:"IsWritable,omitempty"`
	// (Optional) RateLimiter configuration that will be applied to the
	// backing-drive for the VM's rootfs
	RateLimiter *FirecrackerRateLimiter `protobuf:"bytes,4,opt,name=RateLimiter,proto3" json:"RateLimiter,omitempty"`
	// (Optional) CacheType specifies the caching strategy for the block device.
	// The supported caching strategies are: "Unsafe"(default) and "Writeback".
	CacheType            string   `protobuf:"bytes,5,opt,name=CacheType,proto3" json:"CacheType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirecrackerRootDrive) Reset()         { *m = FirecrackerRootDrive{} }
func (m *FirecrackerRootDrive) String() string { return proto.CompactTextString(m) }
func (*FirecrackerRootDrive) ProtoMessage()    {}
func (*FirecrackerRootDrive) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}
func (m *FirecrackerRootDrive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerRootDrive.Unmarshal(m, b)
}
func (m *FirecrackerRootDrive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerRootDrive.Marshal(b, m, deterministic)
}
func (m *FirecrackerRootDrive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerRootDrive.Merge(m, src)
}
func (m *FirecrackerRootDrive) XXX_Size() int {
	return xxx_messageInfo_FirecrackerRootDrive.Size(m)
}
func (m *FirecrackerRootDrive) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerRootDrive.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerRootDrive proto.InternalMessageInfo

func (m *FirecrackerRootDrive) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *FirecrackerRootDrive) GetPartuuid() string {
	if m != nil {
		return m.Partuuid
	}
	return ""
}

func (m *FirecrackerRootDrive) GetIsWritable() bool {
	if m != nil {
		return m.IsWritable
	}
	return false
}

func (m *FirecrackerRootDrive) GetRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.RateLimiter
	}
	return nil
}

func (m *FirecrackerRootDrive) GetCacheType() string {
	if m != nil {
		return m.CacheType
	}
	return ""
}

type FirecrackerDriveMount struct {
	// (Required) HostPath is the path on the host to the filesystem image or device
	// that will be mounted inside the VM.
	HostPath string `protobuf:"bytes,1,opt,name=HostPath,proto3" json:"HostPath,omitempty"`
	// (Required) VMPath is the path inside the VM guest at which the filesystem
	// image or device will be mounted.
	VMPath string `protobuf:"bytes,2,opt,name=VMPath,proto3" json:"VMPath,omitempty"`
	// (Required) FilesystemType is the filesystem type (i.e. ext4, xfs, etc.), as
	// used when mounting the filesystem image inside the VM. The VM guest kernel
	// is expected to have support for this filesystem.
	FilesystemType string `protobuf:"bytes,3,opt,name=FilesystemType,proto3" json:"FilesystemType,omitempty"`
	// (Optional) Options are fstab-style options that the mount will be performed
	// within the VM (i.e. ["rw", "noatime"]). Defaults to none if not specified.
	Options []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	// (Optional) RateLimiter configuration that will be applied to the
	// backing-drive for the VM's rootfs
	RateLimiter *FirecrackerRateLimiter `protobuf:"bytes,5,opt,name=RateLimiter,proto3" json:"RateLimiter,omitempty"`
	// (Optional) If set to true, IsWritable results in the backing file for the
	// drive being opened as read-write by the Firecracker VMM on the host, allowing
	// writes to the image from within the guest. Defaults to false, in which case
	// the block device in the VM will be read-only.
	IsWritable bool `protobuf:"varint,6,opt,name=IsWritable,proto3" json:"IsWritable,omitempty"`
	// (Optional) CacheType specifies the caching strategy for the block device.
	// The supported caching strategies are: "Unsafe"(default) and "Writeback".
	CacheType            string   `protobuf:"bytes,7,opt,name=CacheType,proto3" json:"CacheType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirecrackerDriveMount) Reset()         { *m = FirecrackerDriveMount{} }
func (m *FirecrackerDriveMount) String() string { return proto.CompactTextString(m) }
func (*FirecrackerDriveMount) ProtoMessage()    {}
func (*FirecrackerDriveMount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}
func (m *FirecrackerDriveMount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerDriveMount.Unmarshal(m, b)
}
func (m *FirecrackerDriveMount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerDriveMount.Marshal(b, m, deterministic)
}
func (m *FirecrackerDriveMount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerDriveMount.Merge(m, src)
}
func (m *FirecrackerDriveMount) XXX_Size() int {
	return xxx_messageInfo_FirecrackerDriveMount.Size(m)
}
func (m *FirecrackerDriveMount) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerDriveMount.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerDriveMount proto.InternalMessageInfo

func (m *FirecrackerDriveMount) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *FirecrackerDriveMount) GetVMPath() string {
	if m != nil {
		return m.VMPath
	}
	return ""
}

func (m *FirecrackerDriveMount) GetFilesystemType() string {
	if m != nil {
		return m.FilesystemType
	}
	return ""
}

func (m *FirecrackerDriveMount) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *FirecrackerDriveMount) GetRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.RateLimiter
	}
	return nil
}

func (m *FirecrackerDriveMount) GetIsWritable() bool {
	if m != nil {
		return m.IsWritable
	}
	return false
}

func (m *FirecrackerDriveMount) GetCacheType() string {
	if m != nil {
		return m.CacheType
	}
	return ""
}

// Message to specify an IO rate limiter with bytes/s and ops/s limits
type FirecrackerRateLimiter struct {
	Bandwidth            *FirecrackerTokenBucket `protobuf:"bytes,1,opt,name=Bandwidth,proto3" json:"Bandwidth,omitempty"`
	Ops                  *FirecrackerTokenBucket `protobuf:"bytes,2,opt,name=Ops,proto3" json:"Ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FirecrackerRateLimiter) Reset()         { *m = FirecrackerRateLimiter{} }
func (m *FirecrackerRateLimiter) String() string { return proto.CompactTextString(m) }
func (*FirecrackerRateLimiter) ProtoMessage()    {}
func (*FirecrackerRateLimiter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}
func (m *FirecrackerRateLimiter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerRateLimiter.Unmarshal(m, b)
}
func (m *FirecrackerRateLimiter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerRateLimiter.Marshal(b, m, deterministic)
}
func (m *FirecrackerRateLimiter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerRateLimiter.Merge(m, src)
}
func (m *FirecrackerRateLimiter) XXX_Size() int {
	return xxx_messageInfo_FirecrackerRateLimiter.Size(m)
}
func (m *FirecrackerRateLimiter) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerRateLimiter.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerRateLimiter proto.InternalMessageInfo

func (m *FirecrackerRateLimiter) GetBandwidth() *FirecrackerTokenBucket {
	if m != nil {
		return m.Bandwidth
	}
	return nil
}

func (m *FirecrackerRateLimiter) GetOps() *FirecrackerTokenBucket {
	if m != nil {
		return m.Ops
	}
	return nil
}

// Message to specify a token buicket used to rate limit disk and network IO for a Firecracker VM
type FirecrackerTokenBucket struct {
	OneTimeBurst         int64    `protobuf:"varint,1,opt,name=OneTimeBurst,proto3" json:"OneTimeBurst,omitempty"`
	RefillTime           int64    `protobuf:"varint,2,opt,name=RefillTime,proto3" json:"RefillTime,omitempty"`
	Capacity             int64    `protobuf:"varint,3,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirecrackerTokenBucket) Reset()         { *m = FirecrackerTokenBucket{} }
func (m *FirecrackerTokenBucket) String() string { return proto.CompactTextString(m) }
func (*FirecrackerTokenBucket) ProtoMessage()    {}
func (*FirecrackerTokenBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}
func (m *FirecrackerTokenBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerTokenBucket.Unmarshal(m, b)
}
func (m *FirecrackerTokenBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerTokenBucket.Marshal(b, m, deterministic)
}
func (m *FirecrackerTokenBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerTokenBucket.Merge(m, src)
}
func (m *FirecrackerTokenBucket) XXX_Size() int {
	return xxx_messageInfo_FirecrackerTokenBucket.Size(m)
}
func (m *FirecrackerTokenBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerTokenBucket.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerTokenBucket proto.InternalMessageInfo

func (m *FirecrackerTokenBucket) GetOneTimeBurst() int64 {
	if m != nil {
		return m.OneTimeBurst
	}
	return 0
}

func (m *FirecrackerTokenBucket) GetRefillTime() int64 {
	if m != nil {
		return m.RefillTime
	}
	return 0
}

func (m *FirecrackerTokenBucket) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type FirecrackerBalloonDevice struct {
	AmountMib             int64    `protobuf:"varint,1,opt,name=AmountMib,proto3" json:"AmountMib,omitempty"`
	DeflateOnOom          bool     `protobuf:"varint,2,opt,name=DeflateOnOom,proto3" json:"DeflateOnOom,omitempty"`
	StatsPollingIntervals int64    `protobuf:"varint,3,opt,name=StatsPollingIntervals,proto3" json:"StatsPollingIntervals,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *FirecrackerBalloonDevice) Reset()         { *m = FirecrackerBalloonDevice{} }
func (m *FirecrackerBalloonDevice) String() string { return proto.CompactTextString(m) }
func (*FirecrackerBalloonDevice) ProtoMessage()    {}
func (*FirecrackerBalloonDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}
func (m *FirecrackerBalloonDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerBalloonDevice.Unmarshal(m, b)
}
func (m *FirecrackerBalloonDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerBalloonDevice.Marshal(b, m, deterministic)
}
func (m *FirecrackerBalloonDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerBalloonDevice.Merge(m, src)
}
func (m *FirecrackerBalloonDevice) XXX_Size() int {
	return xxx_messageInfo_FirecrackerBalloonDevice.Size(m)
}
func (m *FirecrackerBalloonDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerBalloonDevice.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerBalloonDevice proto.InternalMessageInfo

func (m *FirecrackerBalloonDevice) GetAmountMib() int64 {
	if m != nil {
		return m.AmountMib
	}
	return 0
}

func (m *FirecrackerBalloonDevice) GetDeflateOnOom() bool {
	if m != nil {
		return m.DeflateOnOom
	}
	return false
}

func (m *FirecrackerBalloonDevice) GetStatsPollingIntervals() int64 {
	if m != nil {
		return m.StatsPollingIntervals
	}
	return 0
}

type MemoryBackend struct {
	BackendType          string   `protobuf:"bytes,1,opt,name=BackendType,proto3" json:"BackendType,omitempty"`
	BackendPath          string   `protobuf:"bytes,2,opt,name=BackendPath,proto3" json:"BackendPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryBackend) Reset()         { *m = MemoryBackend{} }
func (m *MemoryBackend) String() string { return proto.CompactTextString(m) }
func (*MemoryBackend) ProtoMessage()    {}
func (*MemoryBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}
func (m *MemoryBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryBackend.Unmarshal(m, b)
}
func (m *MemoryBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryBackend.Marshal(b, m, deterministic)
}
func (m *MemoryBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryBackend.Merge(m, src)
}
func (m *MemoryBackend) XXX_Size() int {
	return xxx_messageInfo_MemoryBackend.Size(m)
}
func (m *MemoryBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryBackend.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryBackend proto.InternalMessageInfo

func (m *MemoryBackend) GetBackendType() string {
	if m != nil {
		return m.BackendType
	}
	return ""
}

func (m *MemoryBackend) GetBackendPath() string {
	if m != nil {
		return m.BackendPath
	}
	return ""
}

func init() {
	proto.RegisterType((*ExtraData)(nil), "ExtraData")
	proto.RegisterType((*FirecrackerNetworkInterface)(nil), "FirecrackerNetworkInterface")
	proto.RegisterType((*CNIConfiguration)(nil), "CNIConfiguration")
	proto.RegisterType((*CNIConfiguration_CNIArg)(nil), "CNIConfiguration.CNIArg")
	proto.RegisterType((*StaticNetworkConfiguration)(nil), "StaticNetworkConfiguration")
	proto.RegisterType((*IPConfiguration)(nil), "IPConfiguration")
	proto.RegisterType((*FirecrackerMachineConfiguration)(nil), "FirecrackerMachineConfiguration")
	proto.RegisterType((*FirecrackerRootDrive)(nil), "FirecrackerRootDrive")
	proto.RegisterType((*FirecrackerDriveMount)(nil), "FirecrackerDriveMount")
	proto.RegisterType((*FirecrackerRateLimiter)(nil), "FirecrackerRateLimiter")
	proto.RegisterType((*FirecrackerTokenBucket)(nil), "FirecrackerTokenBucket")
	proto.RegisterType((*FirecrackerBalloonDevice)(nil), "FirecrackerBalloonDevice")
	proto.RegisterType((*MemoryBackend)(nil), "MemoryBackend")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 932 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdb, 0x6e, 0x23, 0x45,
	0x13, 0x96, 0x3d, 0xb1, 0x63, 0xb7, 0x93, 0xfd, 0xf3, 0xb7, 0xb2, 0x8b, 0xc9, 0x22, 0xb0, 0x46,
	0x08, 0x19, 0x69, 0xe5, 0xa0, 0x70, 0x90, 0xb8, 0x40, 0x2b, 0x1f, 0x76, 0x59, 0x03, 0x8e, 0xad,
	0x76, 0x08, 0x12, 0x77, 0x9d, 0x71, 0xd9, 0x69, 0x65, 0xa6, 0xdb, 0xea, 0xe9, 0xb1, 0x77, 0xf6,
	0x01, 0xb8, 0x40, 0x5c, 0xf1, 0x02, 0x3c, 0x01, 0x8f, 0xc0, 0x35, 0xaf, 0x85, 0xba, 0xa7, 0x67,
	0xdc, 0xe3, 0x84, 0x48, 0x5c, 0x65, 0xea, 0xab, 0xaa, 0xae, 0xaa, 0xaf, 0x0e, 0x31, 0x6a, 0xa9,
	0x74, 0x0d, 0x71, 0x6f, 0x2d, 0x85, 0x12, 0x67, 0xef, 0xaf, 0x84, 0x58, 0x85, 0x70, 0x6e, 0xa4,
	0x9b, 0x64, 0x79, 0x4e, 0x79, 0x9a, 0xa9, 0xfc, 0xbf, 0x2a, 0xa8, 0xf9, 0xea, 0xad, 0x92, 0x74,
	0x44, 0x15, 0xc5, 0x67, 0xa8, 0xf1, 0x5d, 0x2c, 0xf8, 0x7c, 0x0d, 0x41, 0xbb, 0xd2, 0xa9, 0x74,
	0x8f, 0x48, 0x21, 0xe3, 0xaf, 0x50, 0x8b, 0x24, 0x3c, 0x98, 0xae, 0x15, 0x13, 0x3c, 0x6e, 0x57,
	0x3b, 0x95, 0x6e, 0xeb, 0xe2, 0xb4, 0x97, 0x3d, 0xdd, 0xcb, 0x9f, 0xee, 0xf5, 0x79, 0x4a, 0x5c,
	0x43, 0xfc, 0x01, 0x6a, 0xce, 0xd5, 0x82, 0xf1, 0x99, 0x90, 0xaa, 0xed, 0x75, 0x2a, 0xdd, 0x63,
	0xb2, 0x03, 0xf0, 0x87, 0x08, 0xcd, 0xd5, 0x42, 0x24, 0xca, 0xa8, 0x0f, 0x8c, 0xda, 0x41, 0xac,
	0x1e, 0xa4, 0x34, 0xfa, 0x5a, 0xa1, 0xb7, 0x88, 0xff, 0x67, 0x15, 0x3d, 0x7f, 0xcd, 0x24, 0x04,
	0x92, 0x06, 0x77, 0x20, 0x2f, 0x41, 0x6d, 0x85, 0xbc, 0x1b, 0x73, 0x05, 0x72, 0x49, 0x03, 0xd0,
	0xd1, 0xfb, 0x61, 0x28, 0xb6, 0x93, 0xc9, 0x68, 0x6e, 0x4a, 0x6a, 0x90, 0x1d, 0x80, 0xbf, 0x41,
	0xc7, 0x63, 0x4e, 0xa8, 0x82, 0x1f, 0x58, 0xc4, 0x14, 0x48, 0x5b, 0xd5, 0x7b, 0x3d, 0xe7, 0x49,
	0x47, 0x4d, 0xca, 0xd6, 0xf8, 0x25, 0x7a, 0x32, 0x4d, 0x94, 0xeb, 0xef, 0x3d, 0xee, 0xbf, 0x67,
	0x8e, 0xcf, 0x51, 0x73, 0x78, 0x39, 0x1e, 0x0a, 0xbe, 0x64, 0x2b, 0x53, 0x7c, 0xeb, 0xe2, 0xff,
	0xbd, 0x02, 0x49, 0x24, 0xd5, 0x14, 0x92, 0x9d, 0x0d, 0x7e, 0x89, 0x8e, 0xe6, 0x8a, 0x2a, 0x16,
	0x58, 0x9f, 0x9a, 0xf1, 0x79, 0xde, 0xcb, 0x40, 0x5b, 0x7d, 0xd9, 0xbb, 0xe4, 0xe0, 0xff, 0x5a,
	0x45, 0x27, 0xfb, 0x01, 0x70, 0x07, 0xb5, 0xac, 0xeb, 0x25, 0x8d, 0xc0, 0xd0, 0xd4, 0x24, 0x2e,
	0x84, 0x3f, 0xd6, 0x44, 0x59, 0x4e, 0x8d, 0x4d, 0xd5, 0xd8, 0x94, 0x41, 0xdc, 0x46, 0x87, 0x03,
	0xc6, 0x67, 0x54, 0xdd, 0xb6, 0xbd, 0x8e, 0xd7, 0x6d, 0x92, 0x5c, 0xd4, 0x1a, 0x1d, 0x72, 0xc4,
	0xa4, 0x29, 0xb3, 0x49, 0x72, 0x51, 0x8f, 0xdc, 0x90, 0x06, 0xb7, 0xa0, 0x55, 0x35, 0xa3, 0x2a,
	0x64, 0xfc, 0x02, 0x1d, 0xf4, 0xe5, 0x2a, 0x6e, 0xd7, 0x3b, 0x5e, 0xb7, 0x75, 0xd1, 0xbe, 0xc7,
	0x8c, 0x06, 0xfa, 0x72, 0x45, 0x8c, 0xd5, 0xd9, 0x67, 0xa8, 0x9e, 0xc9, 0xf8, 0x04, 0x79, 0xdf,
	0x43, 0x6a, 0xeb, 0xd0, 0x9f, 0xf8, 0x14, 0xd5, 0xae, 0x69, 0x98, 0xe4, 0x79, 0x67, 0x82, 0xff,
	0x5b, 0x05, 0x9d, 0xfd, 0x3b, 0x73, 0x7a, 0xf6, 0x26, 0x34, 0xe8, 0x2f, 0x16, 0x12, 0xe2, 0xd8,
	0xbe, 0xe6, 0x20, 0x9a, 0xb6, 0x37, 0x22, 0x56, 0x23, 0xd8, 0x38, 0x94, 0xb8, 0x10, 0x7e, 0x81,
	0x1a, 0xe3, 0x99, 0x6d, 0x55, 0x36, 0x1a, 0x27, 0xbd, 0x1c, 0xc8, 0xfb, 0x53, 0x58, 0xf8, 0x5b,
	0xf4, 0xbf, 0x3d, 0xa5, 0x0e, 0x31, 0x93, 0x2c, 0xa2, 0x32, 0xd5, 0x41, 0xf3, 0xce, 0x38, 0x90,
	0xb6, 0xf8, 0x96, 0x2a, 0xd8, 0xd2, 0xcc, 0xc2, 0xcb, 0x2c, 0x1c, 0xc8, 0x74, 0x97, 0x46, 0x10,
	0x83, 0xdc, 0x80, 0x8c, 0xdb, 0x07, 0xa6, 0x33, 0x2e, 0xe4, 0xff, 0x51, 0x41, 0x1f, 0x39, 0x13,
	0x3b, 0xa1, 0xc1, 0x2d, 0xe3, 0x70, 0x2f, 0x93, 0xe1, 0xec, 0xc7, 0x2b, 0x88, 0xd6, 0x21, 0x55,
	0xc5, 0x8c, 0x38, 0x90, 0x5e, 0xb5, 0x37, 0xea, 0x15, 0xa7, 0x37, 0x21, 0x2c, 0x0c, 0x19, 0x0d,
	0xb2, 0x03, 0x0c, 0x99, 0x10, 0xcd, 0xd9, 0x3b, 0x98, 0xb0, 0x1b, 0x7b, 0x07, 0x1c, 0x44, 0x7b,
	0x5f, 0x07, 0xeb, 0x64, 0x28, 0x12, 0x9e, 0xdf, 0x81, 0x1d, 0xe0, 0xff, 0x5d, 0x41, 0xa7, 0xee,
	0x4e, 0x09, 0xa1, 0x46, 0x92, 0x6d, 0x40, 0x8f, 0x8f, 0x26, 0xdc, 0xcc, 0x5c, 0x96, 0x53, 0x21,
	0x6b, 0xdd, 0x8c, 0x4a, 0x95, 0x24, 0x6c, 0x61, 0x9b, 0x53, 0xc8, 0x3a, 0x9d, 0x71, 0xfc, 0x93,
	0x64, 0x4a, 0x67, 0x67, 0xd2, 0x69, 0x10, 0x07, 0xc1, 0x5f, 0xa3, 0x96, 0xbb, 0xd7, 0x07, 0x8f,
	0xef, 0xb5, 0x6b, 0xab, 0x2b, 0x31, 0x13, 0x7c, 0x95, 0xae, 0xc1, 0x8e, 0xf4, 0x0e, 0xf0, 0x7f,
	0xa9, 0xa2, 0xa7, 0xce, 0x2b, 0xa6, 0x8a, 0x89, 0xae, 0xf1, 0xd1, 0x52, 0x9e, 0xa1, 0xfa, 0xf5,
	0xc4, 0x68, 0xb2, 0x42, 0xac, 0x84, 0x3f, 0x41, 0x4f, 0x5e, 0xb3, 0x10, 0xe2, 0x34, 0x56, 0x10,
	0x99, 0x80, 0xd9, 0x00, 0xec, 0xa1, 0x7a, 0xff, 0xf2, 0xc3, 0x9d, 0xf5, 0x3f, 0x17, 0xf7, 0x0b,
	0xad, 0xfd, 0x87, 0x42, 0xcb, 0x1c, 0xd6, 0xef, 0x71, 0x58, 0x22, 0xe2, 0x70, 0x9f, 0x88, 0x77,
	0xe8, 0xd9, 0xc3, 0x41, 0xf0, 0x97, 0xa8, 0x39, 0xa0, 0x7c, 0xb1, 0x65, 0x0b, 0xcb, 0xc4, 0x5e,
	0x42, 0x57, 0xe2, 0x0e, 0xf8, 0x20, 0x09, 0xee, 0x40, 0x91, 0x9d, 0x25, 0xfe, 0x14, 0x79, 0xd3,
	0x75, 0xfc, 0xd0, 0x09, 0x77, 0x1d, 0xb4, 0x8d, 0xff, 0xb6, 0x14, 0xdb, 0x51, 0x63, 0x1f, 0x1d,
	0x4d, 0x39, 0x5c, 0xb1, 0x08, 0x06, 0x89, 0x8c, 0x95, 0x09, 0xef, 0x91, 0x12, 0xa6, 0xeb, 0x26,
	0xb0, 0x64, 0x61, 0xa8, 0x21, 0x13, 0xcf, 0x23, 0x0e, 0x92, 0x9d, 0xb4, 0x35, 0x0d, 0x98, 0x4a,
	0x4d, 0x3b, 0x3c, 0x52, 0xc8, 0xfe, 0xef, 0x15, 0xd4, 0x76, 0x42, 0x0f, 0x68, 0x18, 0x0a, 0xc1,
	0x47, 0xb0, 0x61, 0xf6, 0x9f, 0x55, 0xa4, 0x67, 0x41, 0xaf, 0x48, 0x16, 0x79, 0x07, 0xe8, 0xd4,
	0x46, 0xb0, 0xd4, 0xab, 0x36, 0xe5, 0x53, 0x11, 0xd9, 0x15, 0x2b, 0x61, 0xf8, 0x0b, 0xf4, 0x54,
	0x1f, 0xb4, 0x78, 0x26, 0xc2, 0x90, 0xf1, 0x95, 0x39, 0xcf, 0x1b, 0x1a, 0xc6, 0x36, 0x8f, 0x87,
	0x95, 0xfe, 0x1c, 0x1d, 0x4f, 0x20, 0x12, 0x32, 0x1d, 0xe8, 0xa4, 0xf8, 0x42, 0x2f, 0xbb, 0xfd,
	0x34, 0xbd, 0xb3, 0xcb, 0xee, 0x40, 0x8e, 0x85, 0x33, 0x95, 0x2e, 0x34, 0x38, 0xfc, 0xb9, 0x96,
	0xfd, 0x28, 0xa8, 0x9b, 0x3f, 0x9f, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xea, 0x46, 0x6d, 0xef,
	0x93, 0x08, 0x00, 0x00,
}
