// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message to store bundle/config.json bytes
type ExtraData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonSpec      []byte                 `protobuf:"bytes,1,opt,name=JsonSpec,proto3" json:"JsonSpec,omitempty"`
	RuncOptions   *anypb.Any             `protobuf:"bytes,2,opt,name=RuncOptions,proto3" json:"RuncOptions,omitempty"`
	StdinPort     uint32                 `protobuf:"varint,3,opt,name=StdinPort,proto3" json:"StdinPort,omitempty"`
	StdoutPort    uint32                 `protobuf:"varint,4,opt,name=StdoutPort,proto3" json:"StdoutPort,omitempty"`
	StderrPort    uint32                 `protobuf:"varint,5,opt,name=StderrPort,proto3" json:"StderrPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraData) Reset() {
	*x = ExtraData{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraData) ProtoMessage() {}

func (x *ExtraData) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraData.ProtoReflect.Descriptor instead.
func (*ExtraData) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *ExtraData) GetJsonSpec() []byte {
	if x != nil {
		return x.JsonSpec
	}
	return nil
}

func (x *ExtraData) GetRuncOptions() *anypb.Any {
	if x != nil {
		return x.RuncOptions
	}
	return nil
}

func (x *ExtraData) GetStdinPort() uint32 {
	if x != nil {
		return x.StdinPort
	}
	return 0
}

func (x *ExtraData) GetStdoutPort() uint32 {
	if x != nil {
		return x.StdoutPort
	}
	return 0
}

func (x *ExtraData) GetStderrPort() uint32 {
	if x != nil {
		return x.StderrPort
	}
	return 0
}

// Message to specify network config for a Firecracker VM
type FirecrackerNetworkInterface struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	AllowMMDS      bool                    `protobuf:"varint,1,opt,name=AllowMMDS,proto3" json:"AllowMMDS,omitempty"`          // Specifies if metadata service should be available on this network interface
	InRateLimiter  *FirecrackerRateLimiter `protobuf:"bytes,2,opt,name=InRateLimiter,proto3" json:"InRateLimiter,omitempty"`   // Specifies a rate limiter for incoming bytes
	OutRateLimiter *FirecrackerRateLimiter `protobuf:"bytes,3,opt,name=OutRateLimiter,proto3" json:"OutRateLimiter,omitempty"` // Specifies a rate limiter for outgoing bytes
	// CNIConfiguration specifies CNI configuration that will be used to generate
	// a network interface for a Firecracker VM.
	CNIConfig *CNIConfiguration `protobuf:"bytes,4,opt,name=CNIConfig,proto3" json:"CNIConfig,omitempty"`
	// StaticNetworkConfiguration specifies static configuration parameters for a
	// Firecracker VM's network interface
	StaticConfig  *StaticNetworkConfiguration `protobuf:"bytes,5,opt,name=StaticConfig,proto3" json:"StaticConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirecrackerNetworkInterface) Reset() {
	*x = FirecrackerNetworkInterface{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerNetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerNetworkInterface) ProtoMessage() {}

func (x *FirecrackerNetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerNetworkInterface.ProtoReflect.Descriptor instead.
func (*FirecrackerNetworkInterface) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *FirecrackerNetworkInterface) GetAllowMMDS() bool {
	if x != nil {
		return x.AllowMMDS
	}
	return false
}

func (x *FirecrackerNetworkInterface) GetInRateLimiter() *FirecrackerRateLimiter {
	if x != nil {
		return x.InRateLimiter
	}
	return nil
}

func (x *FirecrackerNetworkInterface) GetOutRateLimiter() *FirecrackerRateLimiter {
	if x != nil {
		return x.OutRateLimiter
	}
	return nil
}

func (x *FirecrackerNetworkInterface) GetCNIConfig() *CNIConfiguration {
	if x != nil {
		return x.CNIConfig
	}
	return nil
}

func (x *FirecrackerNetworkInterface) GetStaticConfig() *StaticNetworkConfiguration {
	if x != nil {
		return x.StaticConfig
	}
	return nil
}

// Message to specify CNI configuration that will be used to
// generate a network interface for a Firecracker VM
type CNIConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NetworkName is the name of a CNI network (as found in CNI
	// configuration files) that will be used to generate the
	// network interface.
	NetworkName string `protobuf:"bytes,1,opt,name=NetworkName,proto3" json:"NetworkName,omitempty"`
	// InterfaceName corresponds to the CNI_IFNAME parameter that will be
	// provided to CNI plugins during invocation.
	InterfaceName string `protobuf:"bytes,2,opt,name=InterfaceName,proto3" json:"InterfaceName,omitempty"`
	// BinPath is a list of directories that will be searched when
	// looking for CNI plugin binaries. Defaults to just "/opt/cni/bin"
	BinPath []string `protobuf:"bytes,3,rep,name=BinPath,proto3" json:"BinPath,omitempty"`
	// ConfDir is the directory in which CNI configuration will be sought.
	// If not specified, will default to "/etc/cni/conf.d".
	ConfDir string `protobuf:"bytes,4,opt,name=ConfDir,proto3" json:"ConfDir,omitempty"`
	// CacheDir is the directory in which CNI results will be temporarily
	// cached by the runtime. If not specified, it will default to
	// "/var/lib/cni"
	CacheDir string `protobuf:"bytes,5,opt,name=CacheDir,proto3" json:"CacheDir,omitempty"`
	// Args corresponds to the CNI_ARGS parameter that will be provided to
	// CNI plugins on invocation.
	Args          []*CNIConfiguration_CNIArg `protobuf:"bytes,6,rep,name=Args,proto3" json:"Args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CNIConfiguration) Reset() {
	*x = CNIConfiguration{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNIConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIConfiguration) ProtoMessage() {}

func (x *CNIConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIConfiguration.ProtoReflect.Descriptor instead.
func (*CNIConfiguration) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *CNIConfiguration) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *CNIConfiguration) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *CNIConfiguration) GetBinPath() []string {
	if x != nil {
		return x.BinPath
	}
	return nil
}

func (x *CNIConfiguration) GetConfDir() string {
	if x != nil {
		return x.ConfDir
	}
	return ""
}

func (x *CNIConfiguration) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *CNIConfiguration) GetArgs() []*CNIConfiguration_CNIArg {
	if x != nil {
		return x.Args
	}
	return nil
}

// Message to specify static configuration parameters for a
// Firecracker VM's network interface
type StaticNetworkConfiguration struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MacAddress  string                 `protobuf:"bytes,1,opt,name=MacAddress,proto3" json:"MacAddress,omitempty"`   // Specifies the mac address for the the device
	HostDevName string                 `protobuf:"bytes,2,opt,name=HostDevName,proto3" json:"HostDevName,omitempty"` // Specifies the name of the tap device on the host
	// IPConfig optionally provides static IP configuration that will be configured
	// on the VM's internal networking interface. If not specified, no IP
	// configuration will be applied to the VM's internal nic automatically.
	IPConfig      *IPConfiguration `protobuf:"bytes,3,opt,name=IPConfig,proto3" json:"IPConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticNetworkConfiguration) Reset() {
	*x = StaticNetworkConfiguration{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticNetworkConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticNetworkConfiguration) ProtoMessage() {}

func (x *StaticNetworkConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticNetworkConfiguration.ProtoReflect.Descriptor instead.
func (*StaticNetworkConfiguration) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *StaticNetworkConfiguration) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *StaticNetworkConfiguration) GetHostDevName() string {
	if x != nil {
		return x.HostDevName
	}
	return ""
}

func (x *StaticNetworkConfiguration) GetIPConfig() *IPConfiguration {
	if x != nil {
		return x.IPConfig
	}
	return nil
}

// Message to specify static IP configuration that will be
// applied to a Firecracker VM's network interface internally
type IPConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PrimaryAddr specifies, in CIDR notation, the primary address
	// and subnet that a network interface will be assigned inside
	// the VM.
	PrimaryAddr string `protobuf:"bytes,1,opt,name=PrimaryAddr,proto3" json:"PrimaryAddr,omitempty"`
	// GatewayAddr specifies the default gateway that a network interface
	// should use inside the VM.
	GatewayAddr string `protobuf:"bytes,3,opt,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
	// Nameservers is a list of nameservers that the VM will be configured
	// to use internally. Currently only up to 2 nameservers can be specified
	// (any more in the list will be ignored) and configuration is provided
	// to the VM via /proc/net/pnp.
	Nameservers   []string `protobuf:"bytes,4,rep,name=Nameservers,proto3" json:"Nameservers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPConfiguration) Reset() {
	*x = IPConfiguration{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPConfiguration) ProtoMessage() {}

func (x *IPConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPConfiguration.ProtoReflect.Descriptor instead.
func (*IPConfiguration) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *IPConfiguration) GetPrimaryAddr() string {
	if x != nil {
		return x.PrimaryAddr
	}
	return ""
}

func (x *IPConfiguration) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

func (x *IPConfiguration) GetNameservers() []string {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

// Message to set the machine config for a Firecracker VM
type FirecrackerMachineConfiguration struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CPUTemplate string                 `protobuf:"bytes,1,opt,name=CPUTemplate,proto3" json:"CPUTemplate,omitempty"` // Specifies the cpu template. Example: "T2" or "C3"
	HtEnabled   bool                   `protobuf:"varint,2,opt,name=HtEnabled,proto3" json:"HtEnabled,omitempty"`    // Specifies if hyper-threading should be enabled
	// Specifies the memory size of VM
	// This lets us create a Firecracker VM of up to 4096 TiB, which
	// for a microVM should be large enough
	MemSizeMib    uint32 `protobuf:"varint,3,opt,name=MemSizeMib,proto3" json:"MemSizeMib,omitempty"`
	VcpuCount     uint32 `protobuf:"varint,4,opt,name=VcpuCount,proto3" json:"VcpuCount,omitempty"` // Specifies the number of vCPUs for the VM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirecrackerMachineConfiguration) Reset() {
	*x = FirecrackerMachineConfiguration{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerMachineConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerMachineConfiguration) ProtoMessage() {}

func (x *FirecrackerMachineConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerMachineConfiguration.ProtoReflect.Descriptor instead.
func (*FirecrackerMachineConfiguration) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *FirecrackerMachineConfiguration) GetCPUTemplate() string {
	if x != nil {
		return x.CPUTemplate
	}
	return ""
}

func (x *FirecrackerMachineConfiguration) GetHtEnabled() bool {
	if x != nil {
		return x.HtEnabled
	}
	return false
}

func (x *FirecrackerMachineConfiguration) GetMemSizeMib() uint32 {
	if x != nil {
		return x.MemSizeMib
	}
	return 0
}

func (x *FirecrackerMachineConfiguration) GetVcpuCount() uint32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

// Message to specify the block device config for a Firecracker VM
type FirecrackerRootDrive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) HostPath is the path on the host to the filesystem image or device
	// that will supply the rootfs of the VM.
	HostPath string `protobuf:"bytes,1,opt,name=HostPath,proto3" json:"HostPath,omitempty"`
	// (Optional) If the HostPath points to a drive or image with multiple
	// partitions, Partuuid specifies which partition will be used to boot
	// the VM
	Partuuid string `protobuf:"bytes,2,opt,name=Partuuid,proto3" json:"Partuuid,omitempty"`
	// (Optional) If set to true, IsWritable results in the VM Guest's rootfs
	// being mounted as read-write. Defaults to false, in which case the
	// rootfs is mounted as read-only.
	IsWritable bool `protobuf:"varint,3,opt,name=IsWritable,proto3" json:"IsWritable,omitempty"`
	// (Optional) RateLimiter configuration that will be applied to the
	// backing-drive for the VM's rootfs
	RateLimiter *FirecrackerRateLimiter `protobuf:"bytes,4,opt,name=RateLimiter,proto3" json:"RateLimiter,omitempty"`
	// (Optional) CacheType specifies the caching strategy for the block device.
	// The supported caching strategies are: "Unsafe"(default) and "Writeback".
	CacheType     string `protobuf:"bytes,5,opt,name=CacheType,proto3" json:"CacheType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirecrackerRootDrive) Reset() {
	*x = FirecrackerRootDrive{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerRootDrive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerRootDrive) ProtoMessage() {}

func (x *FirecrackerRootDrive) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerRootDrive.ProtoReflect.Descriptor instead.
func (*FirecrackerRootDrive) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *FirecrackerRootDrive) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *FirecrackerRootDrive) GetPartuuid() string {
	if x != nil {
		return x.Partuuid
	}
	return ""
}

func (x *FirecrackerRootDrive) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

func (x *FirecrackerRootDrive) GetRateLimiter() *FirecrackerRateLimiter {
	if x != nil {
		return x.RateLimiter
	}
	return nil
}

func (x *FirecrackerRootDrive) GetCacheType() string {
	if x != nil {
		return x.CacheType
	}
	return ""
}

type FirecrackerDriveMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) HostPath is the path on the host to the filesystem image or device
	// that will be mounted inside the VM.
	HostPath string `protobuf:"bytes,1,opt,name=HostPath,proto3" json:"HostPath,omitempty"`
	// (Required) VMPath is the path inside the VM guest at which the filesystem
	// image or device will be mounted.
	VMPath string `protobuf:"bytes,2,opt,name=VMPath,proto3" json:"VMPath,omitempty"`
	// (Required) FilesystemType is the filesystem type (i.e. ext4, xfs, etc.), as
	// used when mounting the filesystem image inside the VM. The VM guest kernel
	// is expected to have support for this filesystem.
	FilesystemType string `protobuf:"bytes,3,opt,name=FilesystemType,proto3" json:"FilesystemType,omitempty"`
	// (Optional) Options are fstab-style options that the mount will be performed
	// within the VM (i.e. ["rw", "noatime"]). Defaults to none if not specified.
	Options []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	// (Optional) RateLimiter configuration that will be applied to the
	// backing-drive for the VM's rootfs
	RateLimiter *FirecrackerRateLimiter `protobuf:"bytes,5,opt,name=RateLimiter,proto3" json:"RateLimiter,omitempty"`
	// (Optional) If set to true, IsWritable results in the backing file for the
	// drive being opened as read-write by the Firecracker VMM on the host, allowing
	// writes to the image from within the guest. Defaults to false, in which case
	// the block device in the VM will be read-only.
	IsWritable bool `protobuf:"varint,6,opt,name=IsWritable,proto3" json:"IsWritable,omitempty"`
	// (Optional) CacheType specifies the caching strategy for the block device.
	// The supported caching strategies are: "Unsafe"(default) and "Writeback".
	CacheType     string `protobuf:"bytes,7,opt,name=CacheType,proto3" json:"CacheType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirecrackerDriveMount) Reset() {
	*x = FirecrackerDriveMount{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerDriveMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerDriveMount) ProtoMessage() {}

func (x *FirecrackerDriveMount) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerDriveMount.ProtoReflect.Descriptor instead.
func (*FirecrackerDriveMount) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *FirecrackerDriveMount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *FirecrackerDriveMount) GetVMPath() string {
	if x != nil {
		return x.VMPath
	}
	return ""
}

func (x *FirecrackerDriveMount) GetFilesystemType() string {
	if x != nil {
		return x.FilesystemType
	}
	return ""
}

func (x *FirecrackerDriveMount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FirecrackerDriveMount) GetRateLimiter() *FirecrackerRateLimiter {
	if x != nil {
		return x.RateLimiter
	}
	return nil
}

func (x *FirecrackerDriveMount) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

func (x *FirecrackerDriveMount) GetCacheType() string {
	if x != nil {
		return x.CacheType
	}
	return ""
}

// Message to specify an IO rate limiter with bytes/s and ops/s limits
type FirecrackerRateLimiter struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Bandwidth     *FirecrackerTokenBucket `protobuf:"bytes,1,opt,name=Bandwidth,proto3" json:"Bandwidth,omitempty"` // Specifies a token bucket with bytes as tokens
	Ops           *FirecrackerTokenBucket `protobuf:"bytes,2,opt,name=Ops,proto3" json:"Ops,omitempty"`             // Specifies a token bucket with operations as tokens
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirecrackerRateLimiter) Reset() {
	*x = FirecrackerRateLimiter{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerRateLimiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerRateLimiter) ProtoMessage() {}

func (x *FirecrackerRateLimiter) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerRateLimiter.ProtoReflect.Descriptor instead.
func (*FirecrackerRateLimiter) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *FirecrackerRateLimiter) GetBandwidth() *FirecrackerTokenBucket {
	if x != nil {
		return x.Bandwidth
	}
	return nil
}

func (x *FirecrackerRateLimiter) GetOps() *FirecrackerTokenBucket {
	if x != nil {
		return x.Ops
	}
	return nil
}

// Message to specify a token buicket used to rate limit disk and network IO for a Firecracker VM
type FirecrackerTokenBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OneTimeBurst  int64                  `protobuf:"varint,1,opt,name=OneTimeBurst,proto3" json:"OneTimeBurst,omitempty"` // Specifies the initial size of the token bucket
	RefillTime    int64                  `protobuf:"varint,2,opt,name=RefillTime,proto3" json:"RefillTime,omitempty"`     // Specifies the amount of millis it takes for the bucket to fill
	Capacity      int64                  `protobuf:"varint,3,opt,name=Capacity,proto3" json:"Capacity,omitempty"`         // Specifies the number of tokens this bucket can hold
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirecrackerTokenBucket) Reset() {
	*x = FirecrackerTokenBucket{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerTokenBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerTokenBucket) ProtoMessage() {}

func (x *FirecrackerTokenBucket) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerTokenBucket.ProtoReflect.Descriptor instead.
func (*FirecrackerTokenBucket) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *FirecrackerTokenBucket) GetOneTimeBurst() int64 {
	if x != nil {
		return x.OneTimeBurst
	}
	return 0
}

func (x *FirecrackerTokenBucket) GetRefillTime() int64 {
	if x != nil {
		return x.RefillTime
	}
	return 0
}

func (x *FirecrackerTokenBucket) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type FirecrackerBalloonDevice struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AmountMib             int64                  `protobuf:"varint,1,opt,name=AmountMib,proto3" json:"AmountMib,omitempty"`                         //Target balloon size in MiB.
	DeflateOnOom          bool                   `protobuf:"varint,2,opt,name=DeflateOnOom,proto3" json:"DeflateOnOom,omitempty"`                   // Whether the balloon should deflate when the guest has memory pressure.
	StatsPollingIntervals int64                  `protobuf:"varint,3,opt,name=StatsPollingIntervals,proto3" json:"StatsPollingIntervals,omitempty"` // Interval in seconds between refreshing statistics.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FirecrackerBalloonDevice) Reset() {
	*x = FirecrackerBalloonDevice{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirecrackerBalloonDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirecrackerBalloonDevice) ProtoMessage() {}

func (x *FirecrackerBalloonDevice) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirecrackerBalloonDevice.ProtoReflect.Descriptor instead.
func (*FirecrackerBalloonDevice) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *FirecrackerBalloonDevice) GetAmountMib() int64 {
	if x != nil {
		return x.AmountMib
	}
	return 0
}

func (x *FirecrackerBalloonDevice) GetDeflateOnOom() bool {
	if x != nil {
		return x.DeflateOnOom
	}
	return false
}

func (x *FirecrackerBalloonDevice) GetStatsPollingIntervals() int64 {
	if x != nil {
		return x.StatsPollingIntervals
	}
	return 0
}

type CNIConfiguration_CNIArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CNIConfiguration_CNIArg) Reset() {
	*x = CNIConfiguration_CNIArg{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNIConfiguration_CNIArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNIConfiguration_CNIArg) ProtoMessage() {}

func (x *CNIConfiguration_CNIArg) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNIConfiguration_CNIArg.ProtoReflect.Descriptor instead.
func (*CNIConfiguration_CNIArg) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CNIConfiguration_CNIArg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CNIConfiguration_CNIArg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x1a\x19google/protobuf/any.proto\"\xbd\x01\n" +
	"\tExtraData\x12\x1a\n" +
	"\bJsonSpec\x18\x01 \x01(\fR\bJsonSpec\x126\n" +
	"\vRuncOptions\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\vRuncOptions\x12\x1c\n" +
	"\tStdinPort\x18\x03 \x01(\rR\tStdinPort\x12\x1e\n" +
	"\n" +
	"StdoutPort\x18\x04 \x01(\rR\n" +
	"StdoutPort\x12\x1e\n" +
	"\n" +
	"StderrPort\x18\x05 \x01(\rR\n" +
	"StderrPort\"\xad\x02\n" +
	"\x1bFirecrackerNetworkInterface\x12\x1c\n" +
	"\tAllowMMDS\x18\x01 \x01(\bR\tAllowMMDS\x12=\n" +
	"\rInRateLimiter\x18\x02 \x01(\v2\x17.FirecrackerRateLimiterR\rInRateLimiter\x12?\n" +
	"\x0eOutRateLimiter\x18\x03 \x01(\v2\x17.FirecrackerRateLimiterR\x0eOutRateLimiter\x12/\n" +
	"\tCNIConfig\x18\x04 \x01(\v2\x11.CNIConfigurationR\tCNIConfig\x12?\n" +
	"\fStaticConfig\x18\x05 \x01(\v2\x1b.StaticNetworkConfigurationR\fStaticConfig\"\x8a\x02\n" +
	"\x10CNIConfiguration\x12 \n" +
	"\vNetworkName\x18\x01 \x01(\tR\vNetworkName\x12$\n" +
	"\rInterfaceName\x18\x02 \x01(\tR\rInterfaceName\x12\x18\n" +
	"\aBinPath\x18\x03 \x03(\tR\aBinPath\x12\x18\n" +
	"\aConfDir\x18\x04 \x01(\tR\aConfDir\x12\x1a\n" +
	"\bCacheDir\x18\x05 \x01(\tR\bCacheDir\x12,\n" +
	"\x04Args\x18\x06 \x03(\v2\x18.CNIConfiguration.CNIArgR\x04Args\x1a0\n" +
	"\x06CNIArg\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"\x8c\x01\n" +
	"\x1aStaticNetworkConfiguration\x12\x1e\n" +
	"\n" +
	"MacAddress\x18\x01 \x01(\tR\n" +
	"MacAddress\x12 \n" +
	"\vHostDevName\x18\x02 \x01(\tR\vHostDevName\x12,\n" +
	"\bIPConfig\x18\x03 \x01(\v2\x10.IPConfigurationR\bIPConfig\"w\n" +
	"\x0fIPConfiguration\x12 \n" +
	"\vPrimaryAddr\x18\x01 \x01(\tR\vPrimaryAddr\x12 \n" +
	"\vGatewayAddr\x18\x03 \x01(\tR\vGatewayAddr\x12 \n" +
	"\vNameservers\x18\x04 \x03(\tR\vNameservers\"\x9f\x01\n" +
	"\x1fFirecrackerMachineConfiguration\x12 \n" +
	"\vCPUTemplate\x18\x01 \x01(\tR\vCPUTemplate\x12\x1c\n" +
	"\tHtEnabled\x18\x02 \x01(\bR\tHtEnabled\x12\x1e\n" +
	"\n" +
	"MemSizeMib\x18\x03 \x01(\rR\n" +
	"MemSizeMib\x12\x1c\n" +
	"\tVcpuCount\x18\x04 \x01(\rR\tVcpuCount\"\xc7\x01\n" +
	"\x14FirecrackerRootDrive\x12\x1a\n" +
	"\bHostPath\x18\x01 \x01(\tR\bHostPath\x12\x1a\n" +
	"\bPartuuid\x18\x02 \x01(\tR\bPartuuid\x12\x1e\n" +
	"\n" +
	"IsWritable\x18\x03 \x01(\bR\n" +
	"IsWritable\x129\n" +
	"\vRateLimiter\x18\x04 \x01(\v2\x17.FirecrackerRateLimiterR\vRateLimiter\x12\x1c\n" +
	"\tCacheType\x18\x05 \x01(\tR\tCacheType\"\x86\x02\n" +
	"\x15FirecrackerDriveMount\x12\x1a\n" +
	"\bHostPath\x18\x01 \x01(\tR\bHostPath\x12\x16\n" +
	"\x06VMPath\x18\x02 \x01(\tR\x06VMPath\x12&\n" +
	"\x0eFilesystemType\x18\x03 \x01(\tR\x0eFilesystemType\x12\x18\n" +
	"\aOptions\x18\x04 \x03(\tR\aOptions\x129\n" +
	"\vRateLimiter\x18\x05 \x01(\v2\x17.FirecrackerRateLimiterR\vRateLimiter\x12\x1e\n" +
	"\n" +
	"IsWritable\x18\x06 \x01(\bR\n" +
	"IsWritable\x12\x1c\n" +
	"\tCacheType\x18\a \x01(\tR\tCacheType\"z\n" +
	"\x16FirecrackerRateLimiter\x125\n" +
	"\tBandwidth\x18\x01 \x01(\v2\x17.FirecrackerTokenBucketR\tBandwidth\x12)\n" +
	"\x03Ops\x18\x02 \x01(\v2\x17.FirecrackerTokenBucketR\x03Ops\"x\n" +
	"\x16FirecrackerTokenBucket\x12\"\n" +
	"\fOneTimeBurst\x18\x01 \x01(\x03R\fOneTimeBurst\x12\x1e\n" +
	"\n" +
	"RefillTime\x18\x02 \x01(\x03R\n" +
	"RefillTime\x12\x1a\n" +
	"\bCapacity\x18\x03 \x01(\x03R\bCapacity\"\x92\x01\n" +
	"\x18FirecrackerBalloonDevice\x12\x1c\n" +
	"\tAmountMib\x18\x01 \x01(\x03R\tAmountMib\x12\"\n" +
	"\fDeflateOnOom\x18\x02 \x01(\bR\fDeflateOnOom\x124\n" +
	"\x15StatsPollingIntervals\x18\x03 \x01(\x03R\x15StatsPollingIntervalsB\tZ\a.;protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_types_proto_goTypes = []any{
	(*ExtraData)(nil),                       // 0: ExtraData
	(*FirecrackerNetworkInterface)(nil),     // 1: FirecrackerNetworkInterface
	(*CNIConfiguration)(nil),                // 2: CNIConfiguration
	(*StaticNetworkConfiguration)(nil),      // 3: StaticNetworkConfiguration
	(*IPConfiguration)(nil),                 // 4: IPConfiguration
	(*FirecrackerMachineConfiguration)(nil), // 5: FirecrackerMachineConfiguration
	(*FirecrackerRootDrive)(nil),            // 6: FirecrackerRootDrive
	(*FirecrackerDriveMount)(nil),           // 7: FirecrackerDriveMount
	(*FirecrackerRateLimiter)(nil),          // 8: FirecrackerRateLimiter
	(*FirecrackerTokenBucket)(nil),          // 9: FirecrackerTokenBucket
	(*FirecrackerBalloonDevice)(nil),        // 10: FirecrackerBalloonDevice
	(*CNIConfiguration_CNIArg)(nil),         // 11: CNIConfiguration.CNIArg
	(*anypb.Any)(nil),                       // 12: google.protobuf.Any
}
var file_types_proto_depIdxs = []int32{
	12, // 0: ExtraData.RuncOptions:type_name -> google.protobuf.Any
	8,  // 1: FirecrackerNetworkInterface.InRateLimiter:type_name -> FirecrackerRateLimiter
	8,  // 2: FirecrackerNetworkInterface.OutRateLimiter:type_name -> FirecrackerRateLimiter
	2,  // 3: FirecrackerNetworkInterface.CNIConfig:type_name -> CNIConfiguration
	3,  // 4: FirecrackerNetworkInterface.StaticConfig:type_name -> StaticNetworkConfiguration
	11, // 5: CNIConfiguration.Args:type_name -> CNIConfiguration.CNIArg
	4,  // 6: StaticNetworkConfiguration.IPConfig:type_name -> IPConfiguration
	8,  // 7: FirecrackerRootDrive.RateLimiter:type_name -> FirecrackerRateLimiter
	8,  // 8: FirecrackerDriveMount.RateLimiter:type_name -> FirecrackerRateLimiter
	9,  // 9: FirecrackerRateLimiter.Bandwidth:type_name -> FirecrackerTokenBucket
	9,  // 10: FirecrackerRateLimiter.Ops:type_name -> FirecrackerTokenBucket
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
