// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: fccontrol.proto

package fccontrol

import (
	proto "github.com/firecracker-microvm/firecracker-containerd/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_fccontrol_proto protoreflect.FileDescriptor

const file_fccontrol_proto_rawDesc = "" +
	"\n" +
	"\x0ffccontrol.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11firecracker.proto2\xa3\a\n" +
	"\vFirecracker\x128\n" +
	"\vPrepareShim\x12\x13.PrepareShimRequest\x1a\x14.PrepareShimResponse\x128\n" +
	"\n" +
	"RemoveShim\x12\x12.RemoveShimRequest\x1a\x16.google.protobuf.Empty\x12/\n" +
	"\bCreateVM\x12\x10.CreateVMRequest\x1a\x11.CreateVMResponse\x122\n" +
	"\aPauseVM\x12\x0f.PauseVMRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\bResumeVM\x12\x10.ResumeVMRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x0eCreateSnapshot\x12\x16.CreateSnapshotRequest\x1a\x16.google.protobuf.Empty\x120\n" +
	"\x06StopVM\x12\x0e.StopVMRequest\x1a\x16.google.protobuf.Empty\x122\n" +
	"\tGetVMInfo\x12\x11.GetVMInfoRequest\x1a\x12.GetVMInfoResponse\x12>\n" +
	"\rSetVMMetadata\x12\x15.SetVMMetadataRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x10UpdateVMMetadata\x12\x18.UpdateVMMetadataRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\rGetVMMetadata\x12\x15.GetVMMetadataRequest\x1a\x16.GetVMMetadataResponse\x12G\n" +
	"\x10GetBalloonConfig\x12\x18.GetBalloonConfigRequest\x1a\x19.GetBalloonConfigResponse\x12>\n" +
	"\rUpdateBalloon\x12\x15.UpdateBalloonRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x0fGetBalloonStats\x12\x17.GetBalloonStatsRequest\x1a\x18.GetBalloonStatsResponse\x12H\n" +
	"\x12UpdateBalloonStats\x12\x1a.UpdateBalloonStatsRequest\x1a\x16.google.protobuf.EmptyB\rZ\v.;fccontrolb\x06proto3"

var file_fccontrol_proto_goTypes = []any{
	(*proto.PrepareShimRequest)(nil),        // 0: PrepareShimRequest
	(*proto.RemoveShimRequest)(nil),         // 1: RemoveShimRequest
	(*proto.CreateVMRequest)(nil),           // 2: CreateVMRequest
	(*proto.PauseVMRequest)(nil),            // 3: PauseVMRequest
	(*proto.ResumeVMRequest)(nil),           // 4: ResumeVMRequest
	(*proto.CreateSnapshotRequest)(nil),     // 5: CreateSnapshotRequest
	(*proto.StopVMRequest)(nil),             // 6: StopVMRequest
	(*proto.GetVMInfoRequest)(nil),          // 7: GetVMInfoRequest
	(*proto.SetVMMetadataRequest)(nil),      // 8: SetVMMetadataRequest
	(*proto.UpdateVMMetadataRequest)(nil),   // 9: UpdateVMMetadataRequest
	(*proto.GetVMMetadataRequest)(nil),      // 10: GetVMMetadataRequest
	(*proto.GetBalloonConfigRequest)(nil),   // 11: GetBalloonConfigRequest
	(*proto.UpdateBalloonRequest)(nil),      // 12: UpdateBalloonRequest
	(*proto.GetBalloonStatsRequest)(nil),    // 13: GetBalloonStatsRequest
	(*proto.UpdateBalloonStatsRequest)(nil), // 14: UpdateBalloonStatsRequest
	(*proto.PrepareShimResponse)(nil),       // 15: PrepareShimResponse
	(*emptypb.Empty)(nil),                   // 16: google.protobuf.Empty
	(*proto.CreateVMResponse)(nil),          // 17: CreateVMResponse
	(*proto.GetVMInfoResponse)(nil),         // 18: GetVMInfoResponse
	(*proto.GetVMMetadataResponse)(nil),     // 19: GetVMMetadataResponse
	(*proto.GetBalloonConfigResponse)(nil),  // 20: GetBalloonConfigResponse
	(*proto.GetBalloonStatsResponse)(nil),   // 21: GetBalloonStatsResponse
}
var file_fccontrol_proto_depIdxs = []int32{
	0,  // 0: Firecracker.PrepareShim:input_type -> PrepareShimRequest
	1,  // 1: Firecracker.RemoveShim:input_type -> RemoveShimRequest
	2,  // 2: Firecracker.CreateVM:input_type -> CreateVMRequest
	3,  // 3: Firecracker.PauseVM:input_type -> PauseVMRequest
	4,  // 4: Firecracker.ResumeVM:input_type -> ResumeVMRequest
	5,  // 5: Firecracker.CreateSnapshot:input_type -> CreateSnapshotRequest
	6,  // 6: Firecracker.StopVM:input_type -> StopVMRequest
	7,  // 7: Firecracker.GetVMInfo:input_type -> GetVMInfoRequest
	8,  // 8: Firecracker.SetVMMetadata:input_type -> SetVMMetadataRequest
	9,  // 9: Firecracker.UpdateVMMetadata:input_type -> UpdateVMMetadataRequest
	10, // 10: Firecracker.GetVMMetadata:input_type -> GetVMMetadataRequest
	11, // 11: Firecracker.GetBalloonConfig:input_type -> GetBalloonConfigRequest
	12, // 12: Firecracker.UpdateBalloon:input_type -> UpdateBalloonRequest
	13, // 13: Firecracker.GetBalloonStats:input_type -> GetBalloonStatsRequest
	14, // 14: Firecracker.UpdateBalloonStats:input_type -> UpdateBalloonStatsRequest
	15, // 15: Firecracker.PrepareShim:output_type -> PrepareShimResponse
	16, // 16: Firecracker.RemoveShim:output_type -> google.protobuf.Empty
	17, // 17: Firecracker.CreateVM:output_type -> CreateVMResponse
	16, // 18: Firecracker.PauseVM:output_type -> google.protobuf.Empty
	16, // 19: Firecracker.ResumeVM:output_type -> google.protobuf.Empty
	16, // 20: Firecracker.CreateSnapshot:output_type -> google.protobuf.Empty
	16, // 21: Firecracker.StopVM:output_type -> google.protobuf.Empty
	18, // 22: Firecracker.GetVMInfo:output_type -> GetVMInfoResponse
	16, // 23: Firecracker.SetVMMetadata:output_type -> google.protobuf.Empty
	16, // 24: Firecracker.UpdateVMMetadata:output_type -> google.protobuf.Empty
	19, // 25: Firecracker.GetVMMetadata:output_type -> GetVMMetadataResponse
	20, // 26: Firecracker.GetBalloonConfig:output_type -> GetBalloonConfigResponse
	16, // 27: Firecracker.UpdateBalloon:output_type -> google.protobuf.Empty
	21, // 28: Firecracker.GetBalloonStats:output_type -> GetBalloonStatsResponse
	16, // 29: Firecracker.UpdateBalloonStats:output_type -> google.protobuf.Empty
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fccontrol_proto_init() }
func file_fccontrol_proto_init() {
	if File_fccontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fccontrol_proto_rawDesc), len(file_fccontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fccontrol_proto_goTypes,
		DependencyIndexes: file_fccontrol_proto_depIdxs,
	}.Build()
	File_fccontrol_proto = out.File
	file_fccontrol_proto_goTypes = nil
	file_fccontrol_proto_depIdxs = nil
}
