// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: drivemount.proto

package drivemount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountDriveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DriveID         string                 `protobuf:"bytes,1,opt,name=DriveID,proto3" json:"DriveID,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=DestinationPath,proto3" json:"DestinationPath,omitempty"`
	FilesytemType   string                 `protobuf:"bytes,3,opt,name=FilesytemType,proto3" json:"FilesytemType,omitempty"`
	Options         []string               `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MountDriveRequest) Reset() {
	*x = MountDriveRequest{}
	mi := &file_drivemount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountDriveRequest) ProtoMessage() {}

func (x *MountDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivemount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountDriveRequest.ProtoReflect.Descriptor instead.
func (*MountDriveRequest) Descriptor() ([]byte, []int) {
	return file_drivemount_proto_rawDescGZIP(), []int{0}
}

func (x *MountDriveRequest) GetDriveID() string {
	if x != nil {
		return x.DriveID
	}
	return ""
}

func (x *MountDriveRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *MountDriveRequest) GetFilesytemType() string {
	if x != nil {
		return x.FilesytemType
	}
	return ""
}

func (x *MountDriveRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type UnmountDriveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveID       string                 `protobuf:"bytes,1,opt,name=DriveID,proto3" json:"DriveID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountDriveRequest) Reset() {
	*x = UnmountDriveRequest{}
	mi := &file_drivemount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountDriveRequest) ProtoMessage() {}

func (x *UnmountDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivemount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountDriveRequest.ProtoReflect.Descriptor instead.
func (*UnmountDriveRequest) Descriptor() ([]byte, []int) {
	return file_drivemount_proto_rawDescGZIP(), []int{1}
}

func (x *UnmountDriveRequest) GetDriveID() string {
	if x != nil {
		return x.DriveID
	}
	return ""
}

var File_drivemount_proto protoreflect.FileDescriptor

const file_drivemount_proto_rawDesc = "" +
	"\n" +
	"\x10drivemount.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x01\n" +
	"\x11MountDriveRequest\x12\x18\n" +
	"\aDriveID\x18\x01 \x01(\tR\aDriveID\x12(\n" +
	"\x0fDestinationPath\x18\x02 \x01(\tR\x0fDestinationPath\x12$\n" +
	"\rFilesytemType\x18\x03 \x01(\tR\rFilesytemType\x12\x18\n" +
	"\aOptions\x18\x04 \x03(\tR\aOptions\"/\n" +
	"\x13UnmountDriveRequest\x12\x18\n" +
	"\aDriveID\x18\x01 \x01(\tR\aDriveID2\x86\x01\n" +
	"\fDriveMounter\x128\n" +
	"\n" +
	"MountDrive\x12\x12.MountDriveRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\fUnmountDrive\x12\x14.UnmountDriveRequest\x1a\x16.google.protobuf.EmptyB\x0eZ\f.;drivemountb\x06proto3"

var (
	file_drivemount_proto_rawDescOnce sync.Once
	file_drivemount_proto_rawDescData []byte
)

func file_drivemount_proto_rawDescGZIP() []byte {
	file_drivemount_proto_rawDescOnce.Do(func() {
		file_drivemount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drivemount_proto_rawDesc), len(file_drivemount_proto_rawDesc)))
	})
	return file_drivemount_proto_rawDescData
}

var file_drivemount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_drivemount_proto_goTypes = []any{
	(*MountDriveRequest)(nil),   // 0: MountDriveRequest
	(*UnmountDriveRequest)(nil), // 1: UnmountDriveRequest
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_drivemount_proto_depIdxs = []int32{
	0, // 0: DriveMounter.MountDrive:input_type -> MountDriveRequest
	1, // 1: DriveMounter.UnmountDrive:input_type -> UnmountDriveRequest
	2, // 2: DriveMounter.MountDrive:output_type -> google.protobuf.Empty
	2, // 3: DriveMounter.UnmountDrive:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drivemount_proto_init() }
func file_drivemount_proto_init() {
	if File_drivemount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drivemount_proto_rawDesc), len(file_drivemount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drivemount_proto_goTypes,
		DependencyIndexes: file_drivemount_proto_depIdxs,
		MessageInfos:      file_drivemount_proto_msgTypes,
	}.Build()
	File_drivemount_proto = out.File
	file_drivemount_proto_goTypes = nil
	file_drivemount_proto_depIdxs = nil
}
